'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace Localize
    
    'Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    '-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    'Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    'mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    '''<summary>
    '''  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Public Class LocFBoxData
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("FBoxDial.LocFBoxData", GetType(LocFBoxData).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        '''  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Fritz!Box Daten ähnelt.
        '''</summary>
        Public Shared ReadOnly Property FBoxDataMainHeader() As String
            Get
                Return ResourceManager.GetString("FBoxDataMainHeader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Nummer auf Anrufsperre der Fritz!Box setzen ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strAddBlockList() As String
            Get
                Return ResourceManager.GetString("strAddBlockList", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Anrufliste ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strAnrList() As String
            Get
                Return ResourceManager.GetString("strAnrList", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Auswählen ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strBrowse() As String
            Get
                Return ResourceManager.GetString("strBrowse", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Anrufen ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strCall() As String
            Get
                Return ResourceManager.GetString("strCall", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Rufsperren ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strCallBarringList() As String
            Get
                Return ResourceManager.GetString("strCallBarringList", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Abbrechen ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strCancel() As String
            Get
                Return ResourceManager.GetString("strCancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Abbruch ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strCancel1() As String
            Get
                Return ResourceManager.GetString("strCancel1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Abbrechen geklickt ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strCancelClicked() As String
            Get
                Return ResourceManager.GetString("strCancelClicked", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Alle auswählen ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strCheckAll() As String
            Get
                Return ResourceManager.GetString("strCheckAll", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Datum ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strDate() As String
            Get
                Return ResourceManager.GetString("strDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Löschen ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strDelete() As String
            Get
                Return ResourceManager.GetString("strDelete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Gerät ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strDevice() As String
            Get
                Return ResourceManager.GetString("strDevice", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Anrufen ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strDial() As String
            Get
                Return ResourceManager.GetString("strDial", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Herunterladen ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strDownload() As String
            Get
                Return ResourceManager.GetString("strDownload", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Fritz!Box Daten ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strDownloader() As String
            Get
                Return ResourceManager.GetString("strDownloader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Dauer ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strDuration() As String
            Get
                Return ResourceManager.GetString("strDuration", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Bearbeiten ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strEdit() As String
            Get
                Return ResourceManager.GetString("strEdit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Endzeit ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strEndTime() As String
            Get
                Return ResourceManager.GetString("strEndTime", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Fritz!Box Anrufliste ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strFBoxAnrufliste() As String
            Get
                Return ResourceManager.GetString("strFBoxAnrufliste", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Fritz!Box Rufsperre ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strFBoxBlockList() As String
            Get
                Return ResourceManager.GetString("strFBoxBlockList", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Filter ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strFilter() As String
            Get
                Return ResourceManager.GetString("strFilter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Fritz!Box Telefonbücher ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strFritzBoxPhonebooks() As String
            Get
                Return ResourceManager.GetString("strFritzBoxPhonebooks", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die E-Mails ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strHeaderMail() As String
            Get
                Return ResourceManager.GetString("strHeaderMail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Telefonnummern ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strHeaderPhone() As String
            Get
                Return ResourceManager.GetString("strHeaderPhone", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Beim Speichern dieses Kontaktes wird das Kontaktbild nicht mehr verfügbar sein. Dies ist ein Fehler in der Firmware der Fritz!Box, welcher bereits an AVM gemeldet und auch bestätigt wurde. Bitte den Kontakt über die Fritz!Box ändern und nicht über dieses Formular. ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strHintBugPicture() As String
            Get
                Return ResourceManager.GetString("strHintBugPicture", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Import der Anrufliste ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strImportCallerList() As String
            Get
                Return ResourceManager.GetString("strImportCallerList", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Jounalimport ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strJournalImport() As String
            Get
                Return ResourceManager.GetString("strJournalImport", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Privat ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strMailHome() As String
            Get
                Return ResourceManager.GetString("strMailHome", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Arbeit ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strMailWork() As String
            Get
                Return ResourceManager.GetString("strMailWork", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Eingene Nr. ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strMyNumber() As String
            Get
                Return ResourceManager.GetString("strMyNumber", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strName() As String
            Get
                Return ResourceManager.GetString("strName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Keine Einträge markiert ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strNoEntriesSelected() As String
            Get
                Return ResourceManager.GetString("strNoEntriesSelected", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Telefonbücher ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strPhonebooks() As String
            Get
                Return ResourceManager.GetString("strPhonebooks", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Privat ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strPhoneHome() As String
            Get
                Return ResourceManager.GetString("strPhoneHome", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Mobil ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strPhoneMobile() As String
            Get
                Return ResourceManager.GetString("strPhoneMobile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Arbeit ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strPhoneWork() As String
            Get
                Return ResourceManager.GetString("strPhoneWork", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Port ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strPort() As String
            Get
                Return ResourceManager.GetString("strPort", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Sollen die selektierten Nummern {0} zu den Rufsperren der Fritz!Box hinzugefügt werden? ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strQuestionBlockNumber() As String
            Get
                Return ResourceManager.GetString("strQuestionBlockNumber", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Soll das Telefonbuch &apos;{0}&apos; auf der Fritz!Box endgültig gelöscht werden? ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strQuestionBookDelete() As String
            Get
                Return ResourceManager.GetString("strQuestionBookDelete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Das Telefonbuch &apos;{0}&apos; kann auf der Fritz!Box nicht gelöscht werden. Stattdessen werden alle Kontakte gelöscht. Fortfahren? ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strQuestionBookDeleteID0() As String
            Get
                Return ResourceManager.GetString("strQuestionBookDeleteID0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Soll diese Rufsperre auf der Fritz!Box endgültig gelöscht werden? ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strQuestionDeleteCallBarring() As String
            Get
                Return ResourceManager.GetString("strQuestionDeleteCallBarring", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Sollen die {0} ausgewählte(n) Einträg(e) aus der Rufsperre endgültig gelöscht werden? ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strQuestionDeleteCallBarrings() As String
            Get
                Return ResourceManager.GetString("strQuestionDeleteCallBarrings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Soll der Kontakt &apos;{0}&apos; im Telefonbuch &apos;{1}&apos; auf der Fritz!Box endgültig gelöscht werden? ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strQuestionDeleteContact() As String
            Get
                Return ResourceManager.GetString("strQuestionDeleteContact", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Sollen die {0} ausgewählte(n) Kontakt(e) im Telefonbuch &apos;{1}&apos; auf der Fritz!Box endgültig gelöscht werden? ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strQuestionDeleteContacts() As String
            Get
                Return ResourceManager.GetString("strQuestionDeleteContacts", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Soll diese Nachricht im Anrufbeantworter auf der Fritz!Box endgültig gelöscht werden? ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strQuestionDeleteMessage() As String
            Get
                Return ResourceManager.GetString("strQuestionDeleteMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Für die Fritz!Box Rufsperre wurden {0} Einträge für {1} Nummern aus der tellows Score-Liste erzeugt (ab Score {2}) . 
        '''
        '''Warnung: Das Hochladen auf die Fritz!Box kann eine Weile dauern und die Fritz!Box kann währenddessen und auch danach träge reagieren.
        '''
        '''Sollen die Einträge jetzt in die Fritz!Box geladen werden? ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strQuestionUpdatetellows() As String
            Get
                Return ResourceManager.GetString("strQuestionUpdatetellows", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Gegenstelle ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strRemoteCaller() As String
            Get
                Return ResourceManager.GetString("strRemoteCaller", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Rufbehandlung ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strRufUml() As String
            Get
                Return ResourceManager.GetString("strRufUml", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Art der Umleitung ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strRufUmlMode() As String
            Get
                Return ResourceManager.GetString("strRufUmlMode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Typ ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strRufUmlTyp() As String
            Get
                Return ResourceManager.GetString("strRufUmlTyp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die über ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strRufUmlVia() As String
            Get
                Return ResourceManager.GetString("strRufUmlVia", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Umleiten von ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strRufUmlVon() As String
            Get
                Return ResourceManager.GetString("strRufUmlVon", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die an ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strRufUmlZiel() As String
            Get
                Return ResourceManager.GetString("strRufUmlZiel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Speichern ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strSave() As String
            Get
                Return ResourceManager.GetString("strSave", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Kontakt anzeigen ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strShowContact() As String
            Get
                Return ResourceManager.GetString("strShowContact", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Starte Jounalimport ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strStartJounalImport() As String
            Get
                Return ResourceManager.GetString("strStartJounalImport", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Startzeit ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strStartTime() As String
            Get
                Return ResourceManager.GetString("strStartTime", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Status ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strStatus() As String
            Get
                Return ResourceManager.GetString("strStatus", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Anrufbeantworter ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTAM() As String
            Get
                Return ResourceManager.GetString("strTAM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Datum ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTAMDate() As String
            Get
                Return ResourceManager.GetString("strTAMDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Dauer ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTAMDuration() As String
            Get
                Return ResourceManager.GetString("strTAMDuration", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Fritz!Box Anrufbeantworter ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTAMHeader() As String
            Get
                Return ResourceManager.GetString("strTAMHeader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTAMName() As String
            Get
                Return ResourceManager.GetString("strTAMName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Telefonnummer ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTAMNumber() As String
            Get
                Return ResourceManager.GetString("strTAMNumber", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Telefonbücher ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTelBuch() As String
            Get
                Return ResourceManager.GetString("strTelBuch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die tellows ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTellows() As String
            Get
                Return ResourceManager.GetString("strTellows", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Nummern hinzufügen ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTellowsAddtoBlockListe() As String
            Get
                Return ResourceManager.GetString("strTellowsAddtoBlockListe", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Mindestscore für Fritz!Box Rufsperre ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTellowsAutoScoreFBBlockList() As String
            Get
                Return ResourceManager.GetString("strTellowsAutoScoreFBBlockList", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTellowsCallerName() As String
            Get
                Return ResourceManager.GetString("strTellowsCallerName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Typ ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTellowsCallerType() As String
            Get
                Return ResourceManager.GetString("strTellowsCallerType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Kommentare ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTellowsComplains() As String
            Get
                Return ResourceManager.GetString("strTellowsComplains", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Rufsperre Einstellungen ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTellowsConfig() As String
            Get
                Return ResourceManager.GetString("strTellowsConfig", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Land ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTellowsCountry() As String
            Get
                Return ResourceManager.GetString("strTellowsCountry", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Anzahl an Telefonnummern je Eintrag ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTellowsEntryNumberCount() As String
            Get
                Return ResourceManager.GetString("strTellowsEntryNumberCount", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Filter ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTellowsFilter() As String
            Get
                Return ResourceManager.GetString("strTellowsFilter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Enthaltener Text in Name oder Typ ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTellowsFilterName() As String
            Get
                Return ResourceManager.GetString("strTellowsFilterName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Anzuzeigender Score ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTellowsFilterScore() As String
            Get
                Return ResourceManager.GetString("strTellowsFilterScore", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Nummer ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTellowsNumber() As String
            Get
                Return ResourceManager.GetString("strTellowsNumber", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Vorwahl ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTellowsPrefix() As String
            Get
                Return ResourceManager.GetString("strTellowsPrefix", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Ort ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTellowsPrefixName() As String
            Get
                Return ResourceManager.GetString("strTellowsPrefixName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Score ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTellowsScore() As String
            Get
                Return ResourceManager.GetString("strTellowsScore", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Suchanfragen ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTellowsSearches() As String
            Get
                Return ResourceManager.GetString("strTellowsSearches", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Zeit ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTime() As String
            Get
                Return ResourceManager.GetString("strTime", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Ein neuen Kontakt hinzufügen... ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strToolTippKontaktAdd() As String
            Get
                Return ResourceManager.GetString("strToolTippKontaktAdd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Diesen Kontakt löschen... ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strToolTippKontaktDel() As String
            Get
                Return ResourceManager.GetString("strToolTippKontaktDel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Diesen Kontakt bearbeiten... ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strToolTippKontaktEdit() As String
            Get
                Return ResourceManager.GetString("strToolTippKontaktEdit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Ein neues Telefonbuch hinzufügen... ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strToolTippTelBuchAdd() As String
            Get
                Return ResourceManager.GetString("strToolTippTelBuchAdd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Dieses Telefonbuch löschen... ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strToolTippTelBuchDel() As String
            Get
                Return ResourceManager.GetString("strToolTippTelBuchDel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Telefonbücher von der Fritz!Box herunterladen... ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strToolTippTelBuchDown() As String
            Get
                Return ResourceManager.GetString("strToolTippTelBuchDown", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Dieses Telefonbuch umbenennen... ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strToolTippTelBuchRename() As String
            Get
                Return ResourceManager.GetString("strToolTippTelBuchRename", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Telefonbücher zur Fritz!Box hochladen... ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strToolTippTelBuchUp() As String
            Get
                Return ResourceManager.GetString("strToolTippTelBuchUp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Keine auswählen ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strUncheckAll() As String
            Get
                Return ResourceManager.GetString("strUncheckAll", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Zeitraum ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strZeitraum() As String
            Get
                Return ResourceManager.GetString("strZeitraum", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
