'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace Localize
    
    'Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    '-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    'Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    'mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    '''<summary>
    '''  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Public Class LocAnrList
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("FBoxDial.LocAnrList", GetType(LocAnrList).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        '''  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Nummer auf Anrufsperre der Fritz!Box setzen ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strAddBlockList() As String
            Get
                Return ResourceManager.GetString("strAddBlockList", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Anrufen ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strCall() As String
            Get
                Return ResourceManager.GetString("strCall", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Abbrechen ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strCancel() As String
            Get
                Return ResourceManager.GetString("strCancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Abbrechen geklickt ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strCancelClicked() As String
            Get
                Return ResourceManager.GetString("strCancelClicked", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Alle auswählen ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strCheckAll() As String
            Get
                Return ResourceManager.GetString("strCheckAll", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Datum ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strDate() As String
            Get
                Return ResourceManager.GetString("strDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Gerät ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strDevice() As String
            Get
                Return ResourceManager.GetString("strDevice", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Herunterladen ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strDownload() As String
            Get
                Return ResourceManager.GetString("strDownload", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Dauer ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strDuration() As String
            Get
                Return ResourceManager.GetString("strDuration", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Endzeit ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strEndTime() As String
            Get
                Return ResourceManager.GetString("strEndTime", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Fritz!Box Anrufliste ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strFBoxAnrufliste() As String
            Get
                Return ResourceManager.GetString("strFBoxAnrufliste", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Fritz!Box Rufsperre ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strFBoxBlockList() As String
            Get
                Return ResourceManager.GetString("strFBoxBlockList", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Import der Anrufliste ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strImportCallerList() As String
            Get
                Return ResourceManager.GetString("strImportCallerList", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Jounalimport ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strJournalImport() As String
            Get
                Return ResourceManager.GetString("strJournalImport", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Eingene Nr. ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strMyNumber() As String
            Get
                Return ResourceManager.GetString("strMyNumber", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strName() As String
            Get
                Return ResourceManager.GetString("strName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Keine Einträge markiert ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strNoEntriesSelected() As String
            Get
                Return ResourceManager.GetString("strNoEntriesSelected", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Port ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strPort() As String
            Get
                Return ResourceManager.GetString("strPort", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Sollen die selektierten Nummern {0} zu den Rufsperren der Fritz!Box hinzugefügt werden? ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strQuestionBlockNumber() As String
            Get
                Return ResourceManager.GetString("strQuestionBlockNumber", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Für die Fritz!Box Rufsperre wurden {0} Einträge für {1} Nummern aus der tellows Score-Liste erzeugt (ab Score {2}) . 
        '''
        '''Warnung: Das Hochladen auf die Fritz!Box kann eine Weile dauern und die Fritz!Box kann währenddessen und auch danach träge reagieren.
        '''
        '''Sollen die Einträge jetzt in die Fritz!Box geladen werden? ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strQuestionUpdatetellows() As String
            Get
                Return ResourceManager.GetString("strQuestionUpdatetellows", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Gegenstelle ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strRemoteCaller() As String
            Get
                Return ResourceManager.GetString("strRemoteCaller", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Kontakt anzeigen ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strShowContact() As String
            Get
                Return ResourceManager.GetString("strShowContact", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Starte Jounalimport ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strStartJounalImport() As String
            Get
                Return ResourceManager.GetString("strStartJounalImport", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Startzeit ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strStartTime() As String
            Get
                Return ResourceManager.GetString("strStartTime", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Status ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strStatus() As String
            Get
                Return ResourceManager.GetString("strStatus", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die tellows ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTellows() As String
            Get
                Return ResourceManager.GetString("strTellows", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Nummern hinzufügen ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTellowsAddtoBlockListe() As String
            Get
                Return ResourceManager.GetString("strTellowsAddtoBlockListe", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Mindestscore für Fritz!Box Rufsperre ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTellowsAutoScoreFBBlockList() As String
            Get
                Return ResourceManager.GetString("strTellowsAutoScoreFBBlockList", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTellowsCallerName() As String
            Get
                Return ResourceManager.GetString("strTellowsCallerName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Typ ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTellowsCallerType() As String
            Get
                Return ResourceManager.GetString("strTellowsCallerType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Kommentare ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTellowsComplains() As String
            Get
                Return ResourceManager.GetString("strTellowsComplains", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Rufsperre Einstellungen ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTellowsConfig() As String
            Get
                Return ResourceManager.GetString("strTellowsConfig", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Land ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTellowsCountry() As String
            Get
                Return ResourceManager.GetString("strTellowsCountry", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Anzahl an Telefonnummern je Eintrag ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTellowsEntryNumberCount() As String
            Get
                Return ResourceManager.GetString("strTellowsEntryNumberCount", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Filter ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTellowsFilter() As String
            Get
                Return ResourceManager.GetString("strTellowsFilter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Enthaltener Text in Name oder Typ ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTellowsFilterName() As String
            Get
                Return ResourceManager.GetString("strTellowsFilterName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Anzuzeigender Score ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTellowsFilterScore() As String
            Get
                Return ResourceManager.GetString("strTellowsFilterScore", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Nummer ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTellowsNumber() As String
            Get
                Return ResourceManager.GetString("strTellowsNumber", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Vorwahl ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTellowsPrefix() As String
            Get
                Return ResourceManager.GetString("strTellowsPrefix", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Ort ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTellowsPrefixName() As String
            Get
                Return ResourceManager.GetString("strTellowsPrefixName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Score ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTellowsScore() As String
            Get
                Return ResourceManager.GetString("strTellowsScore", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Suchanfragen ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTellowsSearches() As String
            Get
                Return ResourceManager.GetString("strTellowsSearches", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Zeit ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTime() As String
            Get
                Return ResourceManager.GetString("strTime", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Keine auswählen ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strUncheckAll() As String
            Get
                Return ResourceManager.GetString("strUncheckAll", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Zeitraum ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strZeitraum() As String
            Get
                Return ResourceManager.GetString("strZeitraum", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
