'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace Localize
    
    'Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    '-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    'Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    'mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    '''<summary>
    '''  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Public Class resTelefonbuch
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("FBoxDial.resTelefonbuch", GetType(resTelefonbuch).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        '''  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Auswählen ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strBrowse() As String
            Get
                Return ResourceManager.GetString("strBrowse", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Rufsperren ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strCallBarringList() As String
            Get
                Return ResourceManager.GetString("strCallBarringList", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Abbruch ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strCancel() As String
            Get
                Return ResourceManager.GetString("strCancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Löschen ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strDelete() As String
            Get
                Return ResourceManager.GetString("strDelete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Bearbeiten ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strEdit() As String
            Get
                Return ResourceManager.GetString("strEdit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Filter ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strFilter() As String
            Get
                Return ResourceManager.GetString("strFilter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Fritz!Box Telefonbücher ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strFritzBoxPhonebooks() As String
            Get
                Return ResourceManager.GetString("strFritzBoxPhonebooks", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die E-Mails ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strHeaderMail() As String
            Get
                Return ResourceManager.GetString("strHeaderMail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Telefonnummern ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strHeaderPhone() As String
            Get
                Return ResourceManager.GetString("strHeaderPhone", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Privat ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strMailHome() As String
            Get
                Return ResourceManager.GetString("strMailHome", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Arbeit ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strMailWork() As String
            Get
                Return ResourceManager.GetString("strMailWork", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Telefonbücher ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strPhonebooks() As String
            Get
                Return ResourceManager.GetString("strPhonebooks", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Privat ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strPhoneHome() As String
            Get
                Return ResourceManager.GetString("strPhoneHome", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Mobil ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strPhoneMobile() As String
            Get
                Return ResourceManager.GetString("strPhoneMobile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Arbeit ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strPhoneWork() As String
            Get
                Return ResourceManager.GetString("strPhoneWork", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Soll das Telefonbuch &apos;{0}&apos; auf der Fritz!Box endgültig gelöscht werden? ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strQuestionBookDelete() As String
            Get
                Return ResourceManager.GetString("strQuestionBookDelete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Das Telefonbuch &apos;{0}&apos; kann auf der Fritz!Box nicht gelöscht werden. Stattdessen werden alle Kontakte gelöscht. Fortfahren? ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strQuestionBookDeleteID0() As String
            Get
                Return ResourceManager.GetString("strQuestionBookDeleteID0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Soll diese Rufsperre auf der Fritz!Box endgültig gelöscht werden? ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strQuestionDeleteCallBarring() As String
            Get
                Return ResourceManager.GetString("strQuestionDeleteCallBarring", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Sollen die (0) ausgewählte(n) Einträg(e) aus der Rufsperre endgültig gelöscht werden? ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strQuestionDeleteCallBarrings() As String
            Get
                Return ResourceManager.GetString("strQuestionDeleteCallBarrings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Soll der Kontakt &apos;{0}&apos; im Telefonbuch &apos;{1}&apos; auf der Fritz!Box endgültig gelöscht werden? ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strQuestionDeleteContact() As String
            Get
                Return ResourceManager.GetString("strQuestionDeleteContact", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Sollen die {0} ausgewählte(n) Kontakt(e) im Telefonbuch &apos;{1}&apos; auf der Fritz!Box endgültig gelöscht werden? ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strQuestionDeleteContacts() As String
            Get
                Return ResourceManager.GetString("strQuestionDeleteContacts", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Speichern ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strSave() As String
            Get
                Return ResourceManager.GetString("strSave", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Ein neuen Kontakt hinzufügen... ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strToolTippKontaktAdd() As String
            Get
                Return ResourceManager.GetString("strToolTippKontaktAdd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Diesen Kontakt löschen... ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strToolTippKontaktDel() As String
            Get
                Return ResourceManager.GetString("strToolTippKontaktDel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Diesen Kontakt bearbeiten... ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strToolTippKontaktEdit() As String
            Get
                Return ResourceManager.GetString("strToolTippKontaktEdit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Ein neues Telefonbuch hinzufügen... ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strToolTippTelBuchAdd() As String
            Get
                Return ResourceManager.GetString("strToolTippTelBuchAdd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Dieses Telefonbuch löschen... ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strToolTippTelBuchDel() As String
            Get
                Return ResourceManager.GetString("strToolTippTelBuchDel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Telefonbücher von der Fritz!Box herunterladen... ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strToolTippTelBuchDown() As String
            Get
                Return ResourceManager.GetString("strToolTippTelBuchDown", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Dieses Telefonbuch umbenennen... ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strToolTippTelBuchRename() As String
            Get
                Return ResourceManager.GetString("strToolTippTelBuchRename", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Telefonbücher zur Fritz!Box hochladen... ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strToolTippTelBuchUp() As String
            Get
                Return ResourceManager.GetString("strToolTippTelBuchUp", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
