'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace Localize
    
    'Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    '-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    'Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    'mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    '''<summary>
    '''  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Public Class LocOptionen
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("FBoxDial.LocOptionen", GetType(LocOptionen).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        '''  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Auswertung der Fritz!Box Anrufliste ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strAnrListHead() As String
            Get
                Return ResourceManager.GetString("strAnrListHead", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Anrufmonitor ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strAnrMon() As String
            Get
                Return ResourceManager.GetString("strAnrMon", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Primärfarbe: Hintergrund
        '''Sekundarfarbe: Schrift ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strAnrMonBColorInfo() As String
            Get
                Return ResourceManager.GetString("strAnrMonBColorInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Anrufmonitor mit Outlook starten ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strAnrMonCBAnrMonAuto() As String
            Get
                Return ResourceManager.GetString("strAnrMonCBAnrMonAuto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Zeige Kontaktbild ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strAnrMonCBAnrMonContactImage() As String
            Get
                Return ResourceManager.GetString("strAnrMonCBAnrMonContactImage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Kontakt bei Anruf öffnen ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strAnrMonCBAnrMonZeigeKontakt() As String
            Get
                Return ResourceManager.GetString("strAnrMonCBAnrMonZeigeKontakt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Anruffenster automatisch ausblenden ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strAnrMonCBAutoClose() As String
            Get
                Return ResourceManager.GetString("strAnrMonCBAutoClose", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Anrufmonitor bei Rufannahme ausblenden ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strAnrMonCBHideCONNECT() As String
            Get
                Return ResourceManager.GetString("strAnrMonCBHideCONNECT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Stoppuhr bei Beenden ausblenden ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strAnrMonCBStoppUhrAusblenden() As String
            Get
                Return ResourceManager.GetString("strAnrMonCBStoppUhrAusblenden", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Stoppuhr bei Verbindungsaufbau einblenden ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strAnrMonCBStoppUhrEinblenden() As String
            Get
                Return ResourceManager.GetString("strAnrMonCBStoppUhrEinblenden", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Einstellungen für den Anrufmonitor ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strAnrMonHeadAnrMon() As String
            Get
                Return ResourceManager.GetString("strAnrMonHeadAnrMon", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Einstellungen für die Stoppuhr ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strAnrMonHeadStoppUhr() As String
            Get
                Return ResourceManager.GetString("strAnrMonHeadStoppUhr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Das Ausblenden des Anrufmonitors wird über einen Timer gesteuert. Normalerweise wird dieser beim eingehenden Telefonat automatisch gestartet. Im Folgenden kann festgelegt werden, dass dieser Timer erst bei dem Zustandekommen der Verbindung gestartet wird. Dies hat zur Folge, dass Anruffenster für verpasste Telefonate geöffnet bleiben. ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strAnrMonHideInfo() As String
            Get
                Return ResourceManager.GetString("strAnrMonHideInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Hier kann die Positionierung des Popups beeinflusst werden. Die Position kann ausgehend von der rechten unteren Ecke des primären Bildschirmes zusätzlich verschoben werden. Zusätzlich kann der Abstand zum Rand und zwischen den einzelnen Popups variiert werden. ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strAnrMonPosInfo() As String
            Get
                Return ResourceManager.GetString("strAnrMonPosInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Setze Hintergrundfarbe des Anrufmonitors ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strAnrMonSetBColor() As String
            Get
                Return ResourceManager.GetString("strAnrMonSetBColor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Setze Hintergrundfarbe der Stoppuhr ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strAnrMonStoppUhrSetBColor() As String
            Get
                Return ResourceManager.GetString("strAnrMonStoppUhrSetBColor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Abstand ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strAnrMonTBAnrMonAbstand() As String
            Get
                Return ResourceManager.GetString("strAnrMonTBAnrMonAbstand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die X-Richtung ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strAnrMonTBAnrMonModPosX() As String
            Get
                Return ResourceManager.GetString("strAnrMonTBAnrMonModPosX", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Y-Richtung ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strAnrMonTBAnrMonModPosY() As String
            Get
                Return ResourceManager.GetString("strAnrMonTBAnrMonModPosY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Anzeigedauer bei Anruf in Sekunden ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strAnrMonTBEnblDauer() As String
            Get
                Return ResourceManager.GetString("strAnrMonTBEnblDauer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Ausblendverzögerung in Sekunden ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strAnrMonTBStoppUhrAusblendverzögerung() As String
            Get
                Return ResourceManager.GetString("strAnrMonTBStoppUhrAusblendverzögerung", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Internationale Vorwahl ergänzen ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strBaseCBintl() As String
            Get
                Return ResourceManager.GetString("strBaseCBintl", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Level ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strBaseCBoxLogLevel() As String
            Get
                Return ResourceManager.GetString("strBaseCBoxLogLevel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Gruppieren ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strBaseCBTelNrGruppieren() As String
            Get
                Return ResourceManager.GetString("strBaseCBTelNrGruppieren", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Grundeinstellung ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strBaseConfig() As String
            Get
                Return ResourceManager.GetString("strBaseConfig", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Grundaten Fritz!Box ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strBaseHeadFB() As String
            Get
                Return ResourceManager.GetString("strBaseHeadFB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Formatierung von Telefonnummern ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strBaseHeadFormatTel() As String
            Get
                Return ResourceManager.GetString("strBaseHeadFormatTel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Anruflisten ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strBaseHeadList() As String
            Get
                Return ResourceManager.GetString("strBaseHeadList", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Protokollierung ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strBaseHeadLog() As String
            Get
                Return ResourceManager.GetString("strBaseHeadLog", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Grundaten Telefonie ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strBaseHeadTel() As String
            Get
                Return ResourceManager.GetString("strBaseHeadTel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Verschiedene Einstellungen ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strBaseHeadTweak() As String
            Get
                Return ResourceManager.GetString("strBaseHeadTweak", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Landes- und Ortskennzahl (jeweils ohne führende Null) werden beim Einlesen der Telefone automatisch aus der Fritz!Box ausgelesen.
        '''Falls keine Werte gefunden wurden, können die Werte hier eingetragen werden. ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strBaseInfoKZ() As String
            Get
                Return ResourceManager.GetString("strBaseInfoKZ", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Öffnen ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strBaseLinkOpen() As String
            Get
                Return ResourceManager.GetString("strBaseLinkOpen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Fritz!Box Benutzername ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strBaseTBBenutzer() As String
            Get
                Return ResourceManager.GetString("strBaseTBBenutzer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Fritz!Box Adresse ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strBaseTBFBAdr() As String
            Get
                Return ResourceManager.GetString("strBaseTBFBAdr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Landeskennzahl ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strBaseTBLandesKZ() As String
            Get
                Return ResourceManager.GetString("strBaseTBLandesKZ", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Anzahl der Listenelemente je Liste ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strBaseTBNumEntryList() As String
            Get
                Return ResourceManager.GetString("strBaseTBNumEntryList", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Ortskennzahl ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strBaseTBOrtsKZ() As String
            Get
                Return ResourceManager.GetString("strBaseTBOrtsKZ", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Fritz!Box Passwort ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strBaseTBPasswort() As String
            Get
                Return ResourceManager.GetString("strBaseTBPasswort", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Maske ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strBaseTBTelNrMaske() As String
            Get
                Return ResourceManager.GetString("strBaseTBTelNrMaske", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die E-Mails nicht prüfen ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strBaseTweakDisableMailCheck() As String
            Get
                Return ResourceManager.GetString("strBaseTweakDisableMailCheck", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Wenn E-Mails verzögert versendet werden, muss folgende Einstellung gesetzt werden, da ansonsten die E-Mails im Postausgang verbleiben und nicht versendet werden. Dies scheint momentan ein Bug im Outlook zu sein. ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strBaseTweakDisableMailCheckInfo() As String
            Get
                Return ResourceManager.GetString("strBaseTweakDisableMailCheckInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Tastatursteuerung aktivieren ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strBaseTweakKeyboard() As String
            Get
                Return ResourceManager.GetString("strBaseTweakKeyboard", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Es besteht die Möglichkeit die Kontaktsuche mittels F2 zu öffnen.
        '''Da dies experimentell ist, kann diese Funktion deaktiviert werden, falls es zu Problemen mit anderen Programmen kommt.
        '''Ein Neustart von Outlook ist erforderlich! ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strBaseTweakKeyboardInfo() As String
            Get
                Return ResourceManager.GetString("strBaseTweakKeyboardInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Timeout der Netzwerkroutinen ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strBaseTweakNetworkTimeout() As String
            Get
                Return ResourceManager.GetString("strBaseTweakNetworkTimeout", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Hier kann der Timeout für die Netzwerkverbindungen (Ping, Downloads etc.) zur Fritz!Box angepasst werden. (Standard: 120 ms) ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strBaseTweakNetworkTimeoutInfo() As String
            Get
                Return ResourceManager.GetString("strBaseTweakNetworkTimeoutInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Arbeitsverzeichnis ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strBaseWorkDir() As String
            Get
                Return ResourceManager.GetString("strBaseWorkDir", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Abbrechen ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strCancel() As String
            Get
                Return ResourceManager.GetString("strCancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Einstellungen ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strConfig() As String
            Get
                Return ResourceManager.GetString("strConfig", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Kontakterstellung ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strCreateContact() As String
            Get
                Return ResourceManager.GetString("strCreateContact", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Kontakte automatisch erstellen ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strCreateContactsCBKErstellen() As String
            Get
                Return ResourceManager.GetString("strCreateContactsCBKErstellen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Keine Daten in die Notizen von Kontakten schreiben ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strCreateContactsCBNoContactNotes() As String
            Get
                Return ResourceManager.GetString("strCreateContactsCBNoContactNotes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Einstellungen für die Kontakterstellung ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strCreateContactsHead() As String
            Get
                Return ResourceManager.GetString("strCreateContactsHead", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Hinweise zur Kontakterstellung:
        '''Sofern Kontakte automatisch erstellt werden sollen, muss hier festgelegt werden, in welchem Ordner die Kontakte gespeichert werden sollen.
        '''Wird kein Ordner gewählt, wird der Outlook-Standard verwendet. ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strCreateContactsInfo() As String
            Get
                Return ResourceManager.GetString("strCreateContactsInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Wählhilfe ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strDialer() As String
            Get
                Return ResourceManager.GetString("strDialer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Nachfrage beim Wählen von Mobilnummern ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strDialerCBCheckMobil() As String
            Get
                Return ResourceManager.GetString("strDialerCBCheckMobil", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Wähldialog automatisch ausblenden ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strDialerCBCloseWClient() As String
            Get
                Return ResourceManager.GetString("strDialerCBCloseWClient", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Landeskennzahl immer mitwählen ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strDialerCBForceDialLKZ() As String
            Get
                Return ResourceManager.GetString("strDialerCBForceDialLKZ", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Einstellungen für den Wählhilfe ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strDialerHead() As String
            Get
                Return ResourceManager.GetString("strDialerHead", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Präfix ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strDialerTBPräfix() As String
            Get
                Return ResourceManager.GetString("strDialerTBPräfix", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Anzeigedauer nach dem Wählen ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strDialerTBWClientEnblDauer() As String
            Get
                Return ResourceManager.GetString("strDialerTBWClientEnblDauer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Status ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strIndexStatus() As String
            Get
                Return ResourceManager.GetString("strIndexStatus", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Info ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strInfo() As String
            Get
                Return ResourceManager.GetString("strInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Es werden keine zugesendeten Informationen an mich oder Dritte weitergeben.
        '''Angaben über das persönliche Telefonieverhalten werden weder ausgewertet noch an Dritte weitergegeben.
        '''Das Programm übermittelt keinerlei Daten an Dritte, jedoch mit folgenden Ausnahmn:
        '''Bei der Rückwärssuche wird die zu Telefonnummer an die ausgewählte Suchmaschine übergeben. Die Datenschutzhinweise der Suchmaschinen sind zu beachten!
        '''Bei der Nutzung von tellows wird die zu Telefonnummer an den Anbieter übergeben. Die Datenschut [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strInfoDatenschutz() As String
            Get
                Return ResourceManager.GetString("strInfoDatenschutz", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Forum ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strInfoForum() As String
            Get
                Return ResourceManager.GetString("strInfoForum", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Github ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strInfoGithub() As String
            Get
                Return ResourceManager.GetString("strInfoGithub", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Ich übernehme keine Haftung für Schäden, die durch das Programm entstanden sind.
        '''Für fehlerhafte oder falsche Angaben, die Rückwärtssuche liefert wird keine Haftung übernommen. ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strInfoHaftung() As String
            Get
                Return ResourceManager.GetString("strInfoHaftung", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Hinweise zum Datenschutz ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strInfoHeadDatenschutz() As String
            Get
                Return ResourceManager.GetString("strInfoHeadDatenschutz", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Hinweise zum Haftungsausschluss ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strInfoHeadHaftung() As String
            Get
                Return ResourceManager.GetString("strInfoHeadHaftung", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Hinweise zum Markenrecht ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strInfoHeadMarkenrecht() As String
            Get
                Return ResourceManager.GetString("strInfoHeadMarkenrecht", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die E-Mail ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strInfoMail() As String
            Get
                Return ResourceManager.GetString("strInfoMail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Dieses Outlook-Addin wird vom Autor privat in der Freizeit als Hobby gepflegt. Mit der Bereitstellung des Outlook-Addins werden keine gewerblichen Interessen verfolgt. Es wird aus rein ideellen Gründen zum Gemeinwohl aller Nutzer einer Fritz!Box betrieben. Die Erstellung dieser Software erfolgt nicht im Auftrag oder mit Wissen der Firmen AVM GmbH bzw. Microsoft Corporation. Diese Software wurde unabhängig erstellt. Der Autor pflegt im Zusammenhang mit dieser Software keine Beziehungen zur Firma AVM GmbH ode [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strInfoMarkenrecht() As String
            Get
                Return ResourceManager.GetString("strInfoMarkenrecht", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Ich habe nun die Möglichkeit geschaffen, mir Spenden zu übersenden. Es besteht in keinem Fall eine Pflicht zu spenden. Es gibt auch keinen Mehrwert für alle, die gespendet haben. Ich programmiere aus Spaß und Freude und nicht zum Zweck des Geldverdienens.
        '''Wer spenden will, der spendet und wer nicht will, der macht es halt nicht. ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strInfoSpende() As String
            Get
                Return ResourceManager.GetString("strInfoSpende", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Spende ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strInfoSpendeHead() As String
            Get
                Return ResourceManager.GetString("strInfoSpendeHead", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die PayPal ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strInfoSpendeLink() As String
            Get
                Return ResourceManager.GetString("strInfoSpendeLink", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Journal ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strJournal() As String
            Get
                Return ResourceManager.GetString("strJournal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Anruflisten aktualisieren ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strJournalCBAnrListeUpdateCallLists() As String
            Get
                Return ResourceManager.GetString("strJournalCBAnrListeUpdateCallLists", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Anrufe aus Fritz!Box bei Outlookstart auswerten ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strJournalCBAutoAnrList() As String
            Get
                Return ResourceManager.GetString("strJournalCBAutoAnrList", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Journaleinträge erstellen ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strJournalCBJournal() As String
            Get
                Return ResourceManager.GetString("strJournalCBJournal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Erfasse auch blockierte Telefonnummern ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strJournalCBJournalBlockNr() As String
            Get
                Return ResourceManager.GetString("strJournalCBJournalBlockNr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Einstellungen für die Journalerstellung ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strJournalHead() As String
            Get
                Return ResourceManager.GetString("strJournalHead", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Hinweise zur Outlook Journaleinträgen:
        '''Sofern Journaleinträge erstellt werden sollen, muss hier festgelegt werden, in welchem Ordner die Einträge erstellt werden sollen.
        '''Wird kein Ordner gewählt, wird der Outlook-Standard verwendet. ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strJournalInfo() As String
            Get
                Return ResourceManager.GetString("strJournalInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die MicroSIP ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strMicroSIP() As String
            Get
                Return ResourceManager.GetString("strMicroSIP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die MicroSIP verwenden ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strMicroSIPCBMicroSIP() As String
            Get
                Return ResourceManager.GetString("strMicroSIPCBMicroSIP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die MicroSIP - Konfiguration ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strMicroSIPHeadConfig() As String
            Get
                Return ResourceManager.GetString("strMicroSIPHeadConfig", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die MicroSIP - Open Source SIP-Softphone ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strMicroSIPHeadInfo() As String
            Get
                Return ResourceManager.GetString("strMicroSIPHeadInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Hinweise zur korrekten Konfiguration:
        '''Stelle sicher, dass MicroSIP sich erfolgreich als ein IP-Telefon an der Fritz!Box registriert hat und lies danach erneut die Telefoniegeräte ein.
        '''Wähle Telefoniegerät aus, was mit MicroSIP registriert ist. ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strMicroSIPInfo() As String
            Get
                Return ResourceManager.GetString("strMicroSIPInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Registriertes Telefon für MicroSIP ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strMicroSIPPhoneInfo() As String
            Get
                Return ResourceManager.GetString("strMicroSIPPhoneInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Pfad zu MicroSIP.exe ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strMicroSIPTBMicroSIPPath() As String
            Get
                Return ResourceManager.GetString("strMicroSIPTBMicroSIPPath", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Aus ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strOFF() As String
            Get
                Return ResourceManager.GetString("strOFF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die An ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strON() As String
            Get
                Return ResourceManager.GetString("strON", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Lade Outlook-Ordner... ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strOutlookTreeView() As String
            Get
                Return ResourceManager.GetString("strOutlookTreeView", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Telefone ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strPhone() As String
            Get
                Return ResourceManager.GetString("strPhone", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Phoner ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strPhoner() As String
            Get
                Return ResourceManager.GetString("strPhoner", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Phoner Copyright 2021 Heiko Sommerfeldt. Alle Rechte vorbehalten. ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strPhonerCopyRight() As String
            Get
                Return ResourceManager.GetString("strPhonerCopyRight", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Phoner - Konfiguration ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strPhonerHeadConfig() As String
            Get
                Return ResourceManager.GetString("strPhonerHeadConfig", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Phoner ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strPhonerHeadInfo() As String
            Get
                Return ResourceManager.GetString("strPhonerHeadInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Die Software ermöglicht Gesprächsverbindungen in das Festnetz, zu Mobiltelefonen und zu VoIP-Gegenstellen. Phoner kann als Softphone an analogen Teilnehmeranschlüssen, an digitalen ISDN Teilnehmeranschlussleitungen und als IP-Softphone auf stationären und mobilen Computersystemen benutzt werden. ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strPhonerInfo() As String
            Get
                Return ResourceManager.GetString("strPhonerInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Hinweise zur korrekten Konfiguration:
        '''Stelle sicher, dass Phoner sich erfolgreich als ein IP-Telefon an der Fritz!Box registriert hat und lies danach erneut die Telefoniegeräte ein.
        '''Lege ein Passwort für die Authentifizierung bei Phoner fest. Das gleiche Passwort muss bei Phoner unter &quot;Optionen / Web&quot; im Feld Passwort eingegeben werden.
        '''Prüfe, ob die Authentifizierung erfolgreich ist.
        '''Wähle Telefoniegerät aus, was mit Phoner registriert ist. ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strPhonerInfoConfig() As String
            Get
                Return ResourceManager.GetString("strPhonerInfoConfig", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die PhonerLight wird nicht unterstützt! ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strPhonerInfoLight() As String
            Get
                Return ResourceManager.GetString("strPhonerInfoLight", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Phoner verwenden ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strPhonerOptCheckBox() As String
            Get
                Return ResourceManager.GetString("strPhonerOptCheckBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Registriertes Telefon für Phoner ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strPhonerstrPhonerPhoneInfo() As String
            Get
                Return ResourceManager.GetString("strPhonerstrPhonerPhoneInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Phoner Passwort ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strPhonerTBPhonerPasswort() As String
            Get
                Return ResourceManager.GetString("strPhonerTBPhonerPasswort", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Speichern ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strSave() As String
            Get
                Return ResourceManager.GetString("strSave", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Kontaktsuche ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strSearchContact() As String
            Get
                Return ResourceManager.GetString("strSearchContact", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Fritz!Box Telefonbüchern einbeziehen ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strSearchContactCBKontaktSucheFritzBox() As String
            Get
                Return ResourceManager.GetString("strSearchContactCBKontaktSucheFritzBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Rückwärtsuche mit DasÖrtliche ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strSearchContactCBRWS() As String
            Get
                Return ResourceManager.GetString("strSearchContactCBRWS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Ergebnisse merken ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strSearchContactCBRWSIndex() As String
            Get
                Return ResourceManager.GetString("strSearchContactCBRWSIndex", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Outlook Unterordner einbeziehen ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strSearchContactCBSucheUnterordner() As String
            Get
                Return ResourceManager.GetString("strSearchContactCBSucheUnterordner", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Deindizieren ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strSearchContactDeIndex() As String
            Get
                Return ResourceManager.GetString("strSearchContactDeIndex", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Outlook Kontaktindizierung ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strSearchContactHeadIndex() As String
            Get
                Return ResourceManager.GetString("strSearchContactHeadIndex", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Rückwärtssuche ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strSearchContactHeadRWS() As String
            Get
                Return ResourceManager.GetString("strSearchContactHeadRWS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Einstellungen für die Kontaktsuche ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strSearchContactHeadSearch() As String
            Get
                Return ResourceManager.GetString("strSearchContactHeadSearch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Indizieren ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strSearchContactIndex() As String
            Get
                Return ResourceManager.GetString("strSearchContactIndex", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Abbruch ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strSearchContactIndexCancel() As String
            Get
                Return ResourceManager.GetString("strSearchContactIndexCancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Start ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strSearchContactIndexStart() As String
            Get
                Return ResourceManager.GetString("strSearchContactIndexStart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Hinweise zur Kontaktsuche:
        '''Es werden nur die hier ausgewählten Ordnern bei der Kontaktsuche berücksichtigt.
        '''Dies verringert die Zeit, bis ein passender Kontakt gefunden wurde.
        '''Die Kontaktindizierung wird nur in den ausgewählten Ordnern automatisch beim Speichern durchgeführt. Sie kann aber auch manuell angestoßen werden.
        '''Wenn ein Ordner nicht mehr für die Kontaktsuche verwendet werden soll, so werden die Indizierungseinträge beim Speichern automatisch entfernt. ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strSearchContactInfo() As String
            Get
                Return ResourceManager.GetString("strSearchContactInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Homepage ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strSoftPhoneHomepage() As String
            Get
                Return ResourceManager.GetString("strSoftPhoneHomepage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Einlesen der Telefoniedaten von der Fritz!Box ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTelephonyHeadImport() As String
            Get
                Return ResourceManager.GetString("strTelephonyHeadImport", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Telefonnummern ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTelephonyHeadNumbers() As String
            Get
                Return ResourceManager.GetString("strTelephonyHeadNumbers", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Telefoniegeräte ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTelephonyHeadPhones() As String
            Get
                Return ResourceManager.GetString("strTelephonyHeadPhones", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Anrufbeantworter ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTelephonyHeadTAM() As String
            Get
                Return ResourceManager.GetString("strTelephonyHeadTAM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Start ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTelephonyImportStart() As String
            Get
                Return ResourceManager.GetString("strTelephonyImportStart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Auswahl der Telefonnummern, auf die der Anrufmonitor reagiert ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTelephonyNumbersInfo() As String
            Get
                Return ResourceManager.GetString("strTelephonyNumbersInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Dialport ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTelephonyPhoneDialport() As String
            Get
                Return ResourceManager.GetString("strTelephonyPhoneDialport", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die ID ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTelephonyPhoneID() As String
            Get
                Return ResourceManager.GetString("strTelephonyPhoneID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Eingehend ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTelephonyPhoneIncomming() As String
            Get
                Return ResourceManager.GetString("strTelephonyPhoneIncomming", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Intern ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTelephonyPhoneIntern() As String
            Get
                Return ResourceManager.GetString("strTelephonyPhoneIntern", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTelephonyPhoneName() As String
            Get
                Return ResourceManager.GetString("strTelephonyPhoneName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Typ ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTelephonyPhoneType() As String
            Get
                Return ResourceManager.GetString("strTelephonyPhoneType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die tellows ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTellows() As String
            Get
                Return ResourceManager.GetString("strTellows", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Anrufmonitor Hintergrund einfärben ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTellowsAnrMonColor() As String
            Get
                Return ResourceManager.GetString("strTellowsAnrMonColor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die API Key ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTellowsAPIKey() As String
            Get
                Return ResourceManager.GetString("strTellowsAPIKey", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die API Key im tellows Shop ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTellowsApiKeyLink() As String
            Get
                Return ResourceManager.GetString("strTellowsApiKeyLink", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Automatisch auf Fritz!Box Rufsperre setzen ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTellowsAutoFBBlockList() As String
            Get
                Return ResourceManager.GetString("strTellowsAutoFBBlockList", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Mindestscore für Fritz!Box Rufsperre ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTellowsAutoScoreFBBlockList() As String
            Get
                Return ResourceManager.GetString("strTellowsAutoScoreFBBlockList", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Fritz!Box Rufsperre automatisch aktualisieren ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTellowsAutoUpdateScoreList() As String
            Get
                Return ResourceManager.GetString("strTellowsAutoUpdateScoreList", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Mögliche Namen ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTellowsCallerNames() As String
            Get
                Return ResourceManager.GetString("strTellowsCallerNames", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Typ ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTellowsCallerTypes() As String
            Get
                Return ResourceManager.GetString("strTellowsCallerTypes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Kontaktsuche bei tellows ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTellowsCBTellows() As String
            Get
                Return ResourceManager.GetString("strTellowsCBTellows", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Anzahl Kommentare dieser Nummer ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTellowsComments() As String
            Get
                Return ResourceManager.GetString("strTellowsComments", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Anzahl an Telefonnummern je Sperrlisteneintrag ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTellowsEntryNumberCount() As String
            Get
                Return ResourceManager.GetString("strTellowsEntryNumberCount", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Fehler! Account Daten nicht geladen. Log prüfen! Ist der API Key korrekt? ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTellowsFehlerPartnerDaten() As String
            Get
                Return ResourceManager.GetString("strTellowsFehlerPartnerDaten", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die tellows - Account Info ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTellowsHeadAccountInfo() As String
            Get
                Return ResourceManager.GetString("strTellowsHeadAccountInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die tellows - Anrufmonitor ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTellowsHeadAnrMon() As String
            Get
                Return ResourceManager.GetString("strTellowsHeadAnrMon", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die tellows - Konfiguration ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTellowsHeadConfig() As String
            Get
                Return ResourceManager.GetString("strTellowsHeadConfig", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die tellows - Fritz!Box Rufsperre ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTellowsHeadFBoxRufsperre() As String
            Get
                Return ResourceManager.GetString("strTellowsHeadFBoxRufsperre", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die tellows - Rückwärtssuche ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTellowsHeadInfo() As String
            Get
                Return ResourceManager.GetString("strTellowsHeadInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Homepage ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTellowsHomepage() As String
            Get
                Return ResourceManager.GetString("strTellowsHomepage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die tellows bietet Informationen zur Identifizierung von seriösen oder gefährlichen Anrufen - dank der weltweiten Community. Die Nutzung von tellows ist nicht kostenfrei. Zur korrekten Nutzung ist der Erwerb eines sogenannten API Keys notwendig. ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTellowsInfo() As String
            Get
                Return ResourceManager.GetString("strTellowsInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Die Rufsperre der Fritz!Box kann durch die Einträge aus tellows ergänzt werden. Es besteht die Möglichkeit, dass ein Abgleich bei Outlookstart (1x aller 24h) erfolgt. Ein manueller Abgleich ist auch über die Anrufliste möglich. Damit nicht für jede Nummer ein Eintrag erzeugt wird, werden die Nummern zu Gruppen zusammengefasst. 
        '''Warnung: Wenn viele Einträge auf die Fritz!Box geladen werden, kann diese träge reagieren.  ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTellowsInfoFBRufsperre() As String
            Get
                Return ResourceManager.GetString("strTellowsInfoFBRufsperre", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Lade Account Daten ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTellowsLadeAccountInfo() As String
            Get
                Return ResourceManager.GetString("strTellowsLadeAccountInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Mindestanzahl an Kommentaren ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTellowsMinComments() As String
            Get
                Return ResourceManager.GetString("strTellowsMinComments", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Mindestscore für Anzeige im Anrufmonitor ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTellowsMinScore() As String
            Get
                Return ResourceManager.GetString("strTellowsMinScore", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Partnerinfo ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTellowsPartnerInfo() As String
            Get
                Return ResourceManager.GetString("strTellowsPartnerInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Partnerlogin ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTellowsPartnerLogin() As String
            Get
                Return ResourceManager.GetString("strTellowsPartnerLogin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Anzahl aller bisherigen Anfragen ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTellowsRequestCount() As String
            Get
                Return ResourceManager.GetString("strTellowsRequestCount", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Score dieser Nummer ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTellowsScore() As String
            Get
                Return ResourceManager.GetString("strTellowsScore", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Anzahl Abfragen dieser Nummer ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTellowsSearches() As String
            Get
                Return ResourceManager.GetString("strTellowsSearches", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Starte Test der Live API ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTellowsStartLiveRequest() As String
            Get
                Return ResourceManager.GetString("strTellowsStartLiveRequest", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die tellows - Test der Live API ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTellowsTest() As String
            Get
                Return ResourceManager.GetString("strTellowsTest", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Testbereich ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTest() As String
            Get
                Return ResourceManager.GetString("strTest", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Anruf verbunden (CONNECT) ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTestAnrMonCONNECT() As String
            Get
                Return ResourceManager.GetString("strTestAnrMonCONNECT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Hier kann die Funktionalität des Anrufmonitors und aller nachgelagerter Funktionen (z. B. Kontaktsuche, Journal) getestet werden. 
        '''Hier werden die selben Funktionen verwendet: Im Journal und der Wahlwiederholungsliste werden diese simulierten Telefonate ebenfalls gelistet. ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTestAnrMonInfo() As String
            Get
                Return ResourceManager.GetString("strTestAnrMonInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Test des Anrufmonitors ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTestAnrufmonitorHead() As String
            Get
                Return ResourceManager.GetString("strTestAnrufmonitorHead", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Alle hier vorhandenen Funktionen dienen zur Fehlersuche und zum Test auf korrekte Funktionalität. Es kann zu Abstürzen kommen: Daher Nutzung auf eigene Gefahr. Sollte hier etwas nicht so funktionieren wie erhofft, dann gebt mir bitte Bescheid.  ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTestInfo() As String
            Get
                Return ResourceManager.GetString("strTestInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Test: Kontaktsuche ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTestKontaktsucheHead() As String
            Get
                Return ResourceManager.GetString("strTestKontaktsucheHead", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Im Folgenden kann die korrekte Umsetzung der Kontaktsuche in den gewälten Outlook Kontoaktordnern getestet werden.
        '''Bei erfolgreicher Suche wird der gefundene Kontakt eingeblendet. ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTestKontaktsucheInfo() As String
            Get
                Return ResourceManager.GetString("strTestKontaktsucheInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Starte die Kontaktsuche ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTestKontaktsucheStart() As String
            Get
                Return ResourceManager.GetString("strTestKontaktsucheStart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Landeskennzahl ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTestLKZ() As String
            Get
                Return ResourceManager.GetString("strTestLKZ", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die ID des Landes ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTestLKZID() As String
            Get
                Return ResourceManager.GetString("strTestLKZID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Name des Landes ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTestLKZName() As String
            Get
                Return ResourceManager.GetString("strTestLKZName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Test: Login Fritz!Box ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTestLoginHead() As String
            Get
                Return ResourceManager.GetString("strTestLoginHead", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Im Folgenden kann das Login-Verfahren getestet werden.
        '''Seit FRITZ!OS 7.24 ist eine Anmeldung auf der Fritz!Box nur noch mit Benutzername und Kennwort möglich. Wenn bisher nur eine Anmeldung allein mit Passwort erfolgte, wurde automatisch ein Benutzer erstellt. ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTestLoginInfo() As String
            Get
                Return ResourceManager.GetString("strTestLoginInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Lade eingerichtete Benutzer der Fritz!Box ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTestLoginLoadUserList() As String
            Get
                Return ResourceManager.GetString("strTestLoginLoadUserList", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Rufnummer unterdrückt (CLIR) ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTestNrUnterdrückt() As String
            Get
                Return ResourceManager.GetString("strTestNrUnterdrückt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Ortsnetzkennzahl ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTestONKZ() As String
            Get
                Return ResourceManager.GetString("strTestONKZ", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Name des Ortsnetzes ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTestONKZName() As String
            Get
                Return ResourceManager.GetString("strTestONKZName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Zufällig ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTestRnd() As String
            Get
                Return ResourceManager.GetString("strTestRnd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Fritz!Box Telefonbücher ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTestRndFBox() As String
            Get
                Return ResourceManager.GetString("strTestRndFBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Zufallskontakt ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTestRndHead() As String
            Get
                Return ResourceManager.GetString("strTestRndHead", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Outlook Kontakte ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTestRndOutlook() As String
            Get
                Return ResourceManager.GetString("strTestRndOutlook", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Tellows ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTestRndTellows() As String
            Get
                Return ResourceManager.GetString("strTestRndTellows", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Test: Rückwärtssuche ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTestRWSHead() As String
            Get
                Return ResourceManager.GetString("strTestRWSHead", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Im Folgenden kann die korrekte Umsetzung der Rückwärtssuche (Inverssuche) getestet werden. ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTestRWSInfo() As String
            Get
                Return ResourceManager.GetString("strTestRWSInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Kein Ergebnis für {0} ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTestRWSNoResult() As String
            Get
                Return ResourceManager.GetString("strTestRWSNoResult", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Starte die Rückwärtssuche ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTestRWSStart() As String
            Get
                Return ResourceManager.GetString("strTestRWSStart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Starte Anrufmonitortest Test ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTestStartAnrMon() As String
            Get
                Return ResourceManager.GetString("strTestStartAnrMon", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Starte Login Test ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTestStartLogin() As String
            Get
                Return ResourceManager.GetString("strTestStartLogin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Durchwahl der Telefonnummer ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTestTelNrDurchwahl() As String
            Get
                Return ResourceManager.GetString("strTestTelNrDurchwahl", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Einwahl der Telefonnummer ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTestTelNrEinwahl() As String
            Get
                Return ResourceManager.GetString("strTestTelNrEinwahl", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Formatierte Telefonnummer ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTestTelNrFormatiert() As String
            Get
                Return ResourceManager.GetString("strTestTelNrFormatiert", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Test: Telefonnummern ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTestTelNrHead() As String
            Get
                Return ResourceManager.GetString("strTestTelNrHead", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Im Folgenden kann die korrekte Umsetzung der Telefonnummernformatierung getestet werden. Telefonnummern müssen korrekt erfasst werden. Zunächst werden alle nicht zur Telefonnummer gehörenden Zeichen entfernt. Danach wird die Telefonnummer hinsichtlich der Kennzahlen (Landeskennzahl, Ortsnetzkenzahl) untersucht. Im letzen Schritt wird die Telefonnummer neu zusammengefügt. ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTestTelNrInfo() As String
            Get
                Return ResourceManager.GetString("strTestTelNrInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Eingabe der Telefonnummer ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTestTelNrInput() As String
            Get
                Return ResourceManager.GetString("strTestTelNrInput", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Telefonnummer auswerten ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTestTelNrStart() As String
            Get
                Return ResourceManager.GetString("strTestTelNrStart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Unformatierte Telefonnummer ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTestTelNrUnformatiert() As String
            Get
                Return ResourceManager.GetString("strTestTelNrUnformatiert", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Zurücksetzen ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strUndo() As String
            Get
                Return ResourceManager.GetString("strUndo", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
