'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.17929
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    '-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    'Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    'mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    '''<summary>
    '''  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("FritzBoxDial.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        '''  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Bild2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Bild2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Bild4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Bild4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Bild5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Bild5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        '''&lt;customUI xmlns=&quot;http://schemas.microsoft.com/office/2009/07/customui&quot; onLoad=&quot;Ribbon_Load&quot;&gt;
        '''  &lt;ribbon&gt;
        '''    &lt;tabs&gt;
        '''      &lt;tab idMso=&quot;TabContacts&quot;&gt;
        '''        &lt;group id=&quot;TabContact&quot; label=&quot;Fritz!Box Telefon-Dingsbums&quot; getVisible=&quot;GroupVisible&quot;&gt;
        '''          &lt;splitButton id=&quot;spb1_C&quot; size=&quot;large&quot;&gt;
        '''            &lt;!--oberste Schaltfläche des SplitButton--&gt;
        '''            &lt;button id=&quot;Button_C1&quot; imageMso=&quot;AutoDial&quot; onAction=&quot;OnActionWählenExplorer&quot; label=&quot;Wählen&quot; screentip=&quot;Frit [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Friend ReadOnly Property RibbonExplorer() As String
            Get
                Return ResourceManager.GetString("RibbonExplorer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        '''&lt;customUI xmlns=&quot;http://schemas.microsoft.com/office/2009/07/customui&quot;&gt;
        '''  &lt;ribbon&gt;
        '''    &lt;tabs&gt;
        '''      &lt;tab idMso=&quot;TabJournal&quot;&gt;
        '''        &lt;group id=&quot;TabJournal&quot; label=&quot;Fritz!Box Telefon-Dingsbums&quot; getVisible=&quot;GroupVisible&quot;&gt;
        '''          &lt;button id=&quot;ButtonJ1&quot; imageMso=&quot;AutoDial&quot; onAction=&quot;OnActionWählen&quot; size=&quot;large&quot; label=&quot;Wählen&quot; screentip=&quot;Fritz!Box Wählclient für Outlook&quot; getEnabled=&quot;ButtonEnableW&quot;/&gt;
        '''           &lt;menu id=&quot;mnu01&quot; size=&quot;large&quot; imageMso=&quot;CheckNames&quot; labe [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Friend ReadOnly Property RibbonJournal() As String
            Get
                Return ResourceManager.GetString("RibbonJournal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        '''&lt;customUI xmlns=&quot;http://schemas.microsoft.com/office/2009/07/customui&quot;&gt;
        '''  &lt;ribbon&gt;
        '''    &lt;tabs&gt;
        '''      &lt;tab idMso=&quot;TabContact&quot;&gt;
        '''        &lt;group id=&quot;TabContact&quot; label=&quot;Fritz!Box Telefon-Dingsbums&quot; getVisible=&quot;GroupVisible&quot;&gt;
        '''          &lt;button id=&quot;ButtonC1&quot; imageMso=&quot;AutoDial&quot; onAction=&quot;OnActionWählen&quot; size=&quot;large&quot; label=&quot;Wählen&quot; screentip=&quot;Fritz!Box Wählclient für Outlook&quot;/&gt;
        '''          &lt;menu id=&quot;mnuC01&quot; size=&quot;large&quot; imageMso=&quot;CheckNames&quot; label=&quot;Rückwärtssuche&quot; screenti [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Friend ReadOnly Property RibbonKontakt() As String
            Get
                Return ResourceManager.GetString("RibbonKontakt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        '''&lt;customUI xmlns=&quot;http://schemas.microsoft.com/office/2009/07/customui&quot;&gt;
        '''  &lt;ribbon&gt;
        '''    &lt;tabs&gt;
        '''      &lt;tab idMso=&quot;TabReadMessage&quot;&gt;
        '''        &lt;group id=&quot;TabReadMessage&quot; label=&quot;Fritz!Box Telefon-Dingsbums&quot; getVisible=&quot;GroupVisible&quot;&gt;
        '''          &lt;button id=&quot;ButtonM1&quot; imageMso=&quot;AutoDial&quot; onAction=&quot;OnActionWählen&quot; size=&quot;large&quot; label=&quot;Wählen&quot; screentip=&quot;Fritz!Box Wählclient für Outlook&quot;/&gt;
        '''        &lt;/group&gt;
        '''      &lt;/tab&gt;
        '''    &lt;/tabs&gt;
        '''  &lt;/ribbon&gt;
        '''&lt;/customUI&gt;
        '''
        ''' ähnelt.
        '''</summary>
        Friend ReadOnly Property RibbonMailRead() As String
            Get
                Return ResourceManager.GetString("RibbonMailRead", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
