'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.34014
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    '-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    'Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    'mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    '''<summary>
    '''  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("FritzBoxDial.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        '''  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &apos;*****************************************************************;;
        '''&apos; Access-Paradies - Tipps, Tricks, Tools, Beispiele für Access;;
        '''&apos; Download von http://www.access-paradies.de;;
        '''&apos;*****************************************************************;;
        '''
        '''93;Afghanistan;
        '''20;Ägypten;
        '''355;Albanien;
        '''213;Algerien;
        '''684;Amerikanisch-Samoa;
        '''1340;Amerikanische Jungferninseln;
        '''376;Andorra;
        '''244;Angola;
        '''1264;Anguilla;
        '''1268;Antigua und Barbuda;
        '''54;Argentinien;
        '''374;Armenien;
        '''297;Aruba;
        '''240;Äquatorial-Guinea [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Friend ReadOnly Property Liste_Landesvorwahlen() As String
            Get
                Return ResourceManager.GetString("Liste_Landesvorwahlen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die 1;915;Abilene Texas;
        '''1;216;Akron Ohio;
        '''1;610;Alameda;
        '''1;912;Albany Georgia;
        '''1;518;Albany New York;
        '''1;505;Albuquerque New Mexico;
        '''1;517;Alpena Michigan;
        '''1;618;Alton Illinois;
        '''1;1809;Amerikanische Jungferninseln;
        '''1;907;Anchorage Alaska;
        '''1;1809;Anguilla;
        '''1;1809;Antigua und Barbuda;
        '''1;617;Arlington Massachusetts;
        '''1;913;Atchison Kansas;
        '''1;404;Atlanta Georgia;
        '''1;609;Atlantic City;
        '''1;315;Auburn New York;
        '''1;207;Auguste Maine;
        '''1;512;Austin Texas;
        '''1;1809;Bahamas;
        '''1;805;Bakersfield California;
        '''1;4 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Friend ReadOnly Property Liste_Ortsvorwahlen_Ausland() As String
            Get
                Return ResourceManager.GetString("Liste_Ortsvorwahlen_Ausland", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &apos;*****************************************************************;
        '''&apos; Access-Paradies - Tipps, Tricks, Tools, Beispiele für Access;
        '''&apos; Download von http://www.access-paradies.de;
        '''&apos;*****************************************************************;
        '''&apos;Und Wikipedia 10.07.14
        '''1010;Dritte HanseStar UG (haftungsbeschränkt);
        '''1011;Ventelo GmbH;
        '''1012;01012 Telecom GmbH;
        '''1013;T&amp;Q Netzbetriebs GmbH &amp; Co. KG;
        '''1014;EWE TEL GmbH;
        '''1015;Maestro Telecom GmbH;
        '''1016;envia TEL GmbH;
        '''1017;Discount Telecom S&amp;V GmbH;
        '''10 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Friend ReadOnly Property Liste_Ortsvorwahlen_Deutschland() As String
            Get
                Return ResourceManager.GetString("Liste_Ortsvorwahlen_Deutschland", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
