'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.296
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    '-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    'Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    'mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    '''<summary>
    '''  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("FritzBoxDial.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        '''  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die 1;USA/Kanada
        '''7;Russland/GUS
        '''20;Ägypten
        '''27;Südafrika
        '''30;Griechenland
        '''31;Niederlande
        '''32;Belgien
        '''33;Frankreich
        '''34;Spanien
        '''36;Ungarn
        '''39;Italien
        '''40;Rumänien
        '''41;Schweiz
        '''43;Österreich
        '''44;Großbritannien und Nordirland
        '''45;Dänemark
        '''46;Schweden
        '''47;Norwegen
        '''48;Polen
        '''49;Deutschland
        '''51;Peru
        '''52;Mexiko
        '''53;Kuba
        '''54;Argentinien
        '''55;Brasilien
        '''56;Chile
        '''57;Kolumbien
        '''58;Venezuela
        '''60;Malaysia
        '''61;Australien
        '''62;Indonesien
        '''63;Philippinen
        '''64;Neuseeland
        '''65;Singapur
        '''66;Thailand
        '''81;Japan
        '''82;Korea (Repub [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Friend ReadOnly Property LandesVorwahlen() As String
            Get
                Return ResourceManager.GetString("LandesVorwahlen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die 30;Berlin
        '''32;VoIP
        '''40;Hamburg
        '''69;Frankfurt a Main
        '''89;München
        '''130;FreeCall
        '''137;T-VoteCall
        '''151;T-Mobile
        '''152;Vodafone
        '''155;E-Plus
        '''1577;E-Plus
        '''159;O2
        '''160;T-Mobile
        '''162;Vodafone
        '''163;E-Plus
        '''170;T-Mobile
        '''171;T-Mobile
        '''172;Vodafone
        '''173;Vodafone
        '''174;Vodafone
        '''175;T-Mobile
        '''176;O2
        '''177;E-Plus
        '''178;E-Plus
        '''179;O2
        '''180;Service Nummer
        '''190;Service Nummer
        '''191;Internet-Einwahl
        '''192;Internet-Einwahl
        '''193;Internet-Einwahl
        '''194;Internet-Einwahl
        '''195;Internet-Einwahl
        '''201;Essen
        '''202;Wuppertal
        '''203;Duisburg
        '''20 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Friend ReadOnly Property Vorwahlen() As String
            Get
                Return ResourceManager.GetString("Vorwahlen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die 1;915;Abilene Texas;
        '''1;216;Akron Ohio;
        '''1;610;Alameda;
        '''1;912;Albany Georgia;
        '''1;518;Albany New York;
        '''1;505;Albuquerque New Mexico;
        '''1;517;Alpena Michigan;
        '''1;618;Alton Illinois;
        '''1;1809;Amerikanische Jungferninseln;
        '''1;907;Anchorage Alaska;
        '''1;1809;Anguilla;
        '''1;1809;Antigua und Barbuda;
        '''1;617;Arlington Massachusetts;
        '''1;913;Atchison Kansas;
        '''1;404;Atlanta Georgia;
        '''1;609;Atlantic City;
        '''1;315;Auburn New York;
        '''1;207;Auguste Maine;
        '''1;512;Austin Texas;
        '''1;1809;Bahamas;
        '''1;805;Bakersfield California;
        '''1;4 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Friend ReadOnly Property VorwahlenAusland() As String
            Get
                Return ResourceManager.GetString("VorwahlenAusland", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
