'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    '-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    'Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    'mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    '''<summary>
    '''  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("FritzBoxDial.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        '''  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die 1
        '''7
        '''20
        '''27
        '''30
        '''31
        '''32
        '''33
        '''34
        '''36
        '''39
        '''40
        '''41
        '''43
        '''44
        '''45
        '''46
        '''47
        '''48
        '''49
        '''51
        '''52
        '''53
        '''54
        '''55
        '''56
        '''57
        '''58
        '''60
        '''61
        '''62
        '''63
        '''64
        '''65
        '''66
        '''81
        '''82
        '''84
        '''86
        '''90
        '''91
        '''92
        '''93
        '''94
        '''95
        '''98
        '''212
        '''213
        '''216
        '''218
        '''220
        '''221
        '''222
        '''223
        '''224
        '''225
        '''226
        '''227
        '''228
        '''229
        '''230
        '''231
        '''232
        '''233
        '''234
        '''235
        '''236
        '''237
        '''238
        '''239
        '''240
        '''241
        '''242
        '''243
        '''244
        '''245
        '''247
        '''248
        '''249
        '''250
        '''251
        '''252
        '''253
        '''254
        '''255
        '''256
        '''257
        '''258
        '''260
        '''261
        '''262
        '''263
        '''264
        '''265
        '''266
        '''267
        '''268
        '''269
        '''290
        '''291
        '''297
        '''298
        '''299
        '''350
        '''351
        '''352
        '''353
        '''354
        '''355
        '''356
        '''357
        '''358
        ''' [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Friend ReadOnly Property Liste_Landesvorwahlen() As String
            Get
                Return ResourceManager.GetString("Liste_Landesvorwahlen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die 1:915
        '''1:216
        '''1:610
        '''1:912
        '''1:518
        '''1:505
        '''1:517
        '''1:618
        '''1:1809
        '''1:907
        '''1:617
        '''1:913
        '''1:404
        '''1:609
        '''1:315
        '''1:207
        '''1:512
        '''1:805
        '''1:410
        '''1:403
        '''1:918
        '''1:504
        '''1:409
        '''1:310
        '''1:701
        '''1:208
        '''1:204
        '''1:718
        '''1:716
        '''1:702
        '''1:304
        '''1:704
        '''1:804
        '''1:902
        '''1:615
        '''1:307
        '''1:312
        '''1:916
        '''1:513
        '''1:719
        '''1:803
        '''1:706
        '''1:614
        '''1:603
        '''1:709
        '''1:214
        '''1:319
        '''1:904
        '''1:210
        '''1:903
        '''1:817
        '''1:303
        '''1:515
        '''1:313
        '''1:316
        '''1:302
        '''1:901
        '''1:506
        '''1:915
        '''1:607
        '''1:707
        '''1:206
        '''1:305
        '''1:604
        '''1:508
        '''1:502
        '''1:919
        '''1:910
        '''1:905
        '''1:209
        '''1:203
        '''1:406
        '''1:717
        ''' [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Friend ReadOnly Property Liste_Ortsvorwahlen_Ausland() As String
            Get
                Return ResourceManager.GetString("Liste_Ortsvorwahlen_Ausland", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die 30
        '''32
        '''40
        '''69
        '''89
        '''130
        '''137
        '''138
        '''150
        '''151
        '''152
        '''153
        '''154
        '''155
        '''156
        '''157
        '''158
        '''159
        '''160
        '''161
        '''162
        '''163
        '''164
        '''165
        '''166
        '''167
        '''168
        '''169
        '''170
        '''171
        '''172
        '''173
        '''174
        '''175
        '''176
        '''177
        '''178
        '''179
        '''180
        '''181
        '''182
        '''183
        '''184
        '''185
        '''186
        '''187
        '''188
        '''189
        '''190
        '''191
        '''192
        '''193
        '''194
        '''199
        '''201
        '''202
        '''203
        '''208
        '''209
        '''211
        '''212
        '''214
        '''221
        '''228
        '''231
        '''234
        '''241
        '''251
        '''261
        '''271
        '''281
        '''291
        '''331
        '''335
        '''340
        '''341
        '''345
        '''351
        '''355
        '''361
        '''365
        '''371
        '''375
        '''381
        '''385
        '''391
        '''395
        '''421
        '''431
        '''441
        '''451
        '''461
        '''471
        '''481
        '''491
        '''511
        '''521
        '''531
        '''541
        '''551
        '''561
        '''571
        '''581
        '''59 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Friend ReadOnly Property Liste_Ortsvorwahlen_Deutschland() As String
            Get
                Return ResourceManager.GetString("Liste_Ortsvorwahlen_Deutschland", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
