'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace Localize
    
    'Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    '-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    'Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    'mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    '''<summary>
    '''  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Länder
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("FBoxDial.Länder", GetType(Länder).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        '''  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Samoa (amerikanisch) ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property _AS() As String
            Get
                Return ResourceManager.GetString("AS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Dominikanische Republik ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property _DO() As String
            Get
                Return ResourceManager.GetString("DO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Indien ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property _IN() As String
            Get
                Return ResourceManager.GetString("IN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Island ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property _IS() As String
            Get
                Return ResourceManager.GetString("IS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Montenegro ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property _ME() As String
            Get
                Return ResourceManager.GetString("ME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Tonga ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property _TO() As String
            Get
                Return ResourceManager.GetString("TO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Andorra ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property AD() As String
            Get
                Return ResourceManager.GetString("AD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Vereinigte Arabische Emirate ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property AE() As String
            Get
                Return ResourceManager.GetString("AE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Afghanistan ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property AF() As String
            Get
                Return ResourceManager.GetString("AF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Antigua und Barbuda ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property AG() As String
            Get
                Return ResourceManager.GetString("AG", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Anguilla ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property AI() As String
            Get
                Return ResourceManager.GetString("AI", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Albanien ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property AL() As String
            Get
                Return ResourceManager.GetString("AL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Armenien ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property AM() As String
            Get
                Return ResourceManager.GetString("AM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Niederländische Antillen ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property AN() As String
            Get
                Return ResourceManager.GetString("AN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Angola ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property AO() As String
            Get
                Return ResourceManager.GetString("AO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Antarktis ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property AQ() As String
            Get
                Return ResourceManager.GetString("AQ", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Argentinien ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property AR() As String
            Get
                Return ResourceManager.GetString("AR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Österreich ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property AT() As String
            Get
                Return ResourceManager.GetString("AT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Australien ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property AU() As String
            Get
                Return ResourceManager.GetString("AU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Aruba ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property AW() As String
            Get
                Return ResourceManager.GetString("AW", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Ålandinseln ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property AX() As String
            Get
                Return ResourceManager.GetString("AX", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Aserbaidschan ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property AZ() As String
            Get
                Return ResourceManager.GetString("AZ", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Bosnien-Herzegowina ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property BA() As String
            Get
                Return ResourceManager.GetString("BA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Barbados ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property BB() As String
            Get
                Return ResourceManager.GetString("BB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Bangladesh ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property BD() As String
            Get
                Return ResourceManager.GetString("BD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Belgien ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property BE() As String
            Get
                Return ResourceManager.GetString("BE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Burkina Faso ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property BF() As String
            Get
                Return ResourceManager.GetString("BF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Bulgarien ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property BG() As String
            Get
                Return ResourceManager.GetString("BG", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Bahrain ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property BH() As String
            Get
                Return ResourceManager.GetString("BH", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Burundi ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property BI() As String
            Get
                Return ResourceManager.GetString("BI", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Benin ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property BJ() As String
            Get
                Return ResourceManager.GetString("BJ", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Bermudas ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property BM() As String
            Get
                Return ResourceManager.GetString("BM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Brunei ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property BN() As String
            Get
                Return ResourceManager.GetString("BN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Bolivien ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property BO() As String
            Get
                Return ResourceManager.GetString("BO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Brasilien ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property BR() As String
            Get
                Return ResourceManager.GetString("BR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Bahamas ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property BS() As String
            Get
                Return ResourceManager.GetString("BS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Bhutan ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property BT() As String
            Get
                Return ResourceManager.GetString("BT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Bouvet Inseln ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property BV() As String
            Get
                Return ResourceManager.GetString("BV", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Botswana ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property BW() As String
            Get
                Return ResourceManager.GetString("BW", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Weißrußland ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property BY() As String
            Get
                Return ResourceManager.GetString("BY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Belize ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property BZ() As String
            Get
                Return ResourceManager.GetString("BZ", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Kanada ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property CA() As String
            Get
                Return ResourceManager.GetString("CA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Kokosinseln ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property CC() As String
            Get
                Return ResourceManager.GetString("CC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Kongo, Demokratische Republik ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property CD() As String
            Get
                Return ResourceManager.GetString("CD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Zentralafrikanische Republik ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property CF() As String
            Get
                Return ResourceManager.GetString("CF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Kongo ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property CG() As String
            Get
                Return ResourceManager.GetString("CG", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Schweiz ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property CH() As String
            Get
                Return ResourceManager.GetString("CH", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Elfenbeinküste ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property CI() As String
            Get
                Return ResourceManager.GetString("CI", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Cook Inseln ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property CK() As String
            Get
                Return ResourceManager.GetString("CK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Chile ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property CL() As String
            Get
                Return ResourceManager.GetString("CL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Kamerun ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property CM() As String
            Get
                Return ResourceManager.GetString("CM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die China ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property CN() As String
            Get
                Return ResourceManager.GetString("CN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Kolumbien ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property CO() As String
            Get
                Return ResourceManager.GetString("CO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Costa Rica ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property CR() As String
            Get
                Return ResourceManager.GetString("CR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Kuba ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property CU() As String
            Get
                Return ResourceManager.GetString("CU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Kap Verde ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property CV() As String
            Get
                Return ResourceManager.GetString("CV", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Weinachtsinseln ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property CX() As String
            Get
                Return ResourceManager.GetString("CX", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Zypern ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property CY() As String
            Get
                Return ResourceManager.GetString("CY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Tschechische Republik ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property CZ() As String
            Get
                Return ResourceManager.GetString("CZ", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Deutschland ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DE() As String
            Get
                Return ResourceManager.GetString("DE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Djibuti ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DJ() As String
            Get
                Return ResourceManager.GetString("DJ", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Dänemark ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DK() As String
            Get
                Return ResourceManager.GetString("DK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Dominika ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DM() As String
            Get
                Return ResourceManager.GetString("DM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Algerien ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DZ() As String
            Get
                Return ResourceManager.GetString("DZ", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Ecuador ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property EC() As String
            Get
                Return ResourceManager.GetString("EC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Estland ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property EE() As String
            Get
                Return ResourceManager.GetString("EE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Ägypten ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property EG() As String
            Get
                Return ResourceManager.GetString("EG", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Westsahara ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property EH() As String
            Get
                Return ResourceManager.GetString("EH", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Eritrea ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ER() As String
            Get
                Return ResourceManager.GetString("ER", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Spanien ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ES() As String
            Get
                Return ResourceManager.GetString("ES", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Äthiopien ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ET() As String
            Get
                Return ResourceManager.GetString("ET", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Finnland ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property FI() As String
            Get
                Return ResourceManager.GetString("FI", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Fidschi ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property FJ() As String
            Get
                Return ResourceManager.GetString("FJ", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Falkland Inseln ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property FK() As String
            Get
                Return ResourceManager.GetString("FK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Mikronesien ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property FM() As String
            Get
                Return ResourceManager.GetString("FM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Färöer Inseln ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property FO() As String
            Get
                Return ResourceManager.GetString("FO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Frankreich ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property FR() As String
            Get
                Return ResourceManager.GetString("FR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Gabun ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property GA() As String
            Get
                Return ResourceManager.GetString("GA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Großbritannien(GB) ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property GB() As String
            Get
                Return ResourceManager.GetString("GB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Grenada ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property GD() As String
            Get
                Return ResourceManager.GetString("GD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Georgien ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property GE() As String
            Get
                Return ResourceManager.GetString("GE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die französisch Guyana ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property GF() As String
            Get
                Return ResourceManager.GetString("GF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Ghana ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property GH() As String
            Get
                Return ResourceManager.GetString("GH", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Gibraltar ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property GI() As String
            Get
                Return ResourceManager.GetString("GI", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Grönland ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property GL() As String
            Get
                Return ResourceManager.GetString("GL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Gambia ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property GM() As String
            Get
                Return ResourceManager.GetString("GM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Guinea ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property GN() As String
            Get
                Return ResourceManager.GetString("GN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Guadeloupe ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property GP() As String
            Get
                Return ResourceManager.GetString("GP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Äquatorial Guinea ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property GQ() As String
            Get
                Return ResourceManager.GetString("GQ", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Griechenland ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property GR() As String
            Get
                Return ResourceManager.GetString("GR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die South Georgia, South Sandwich Isl. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property GS() As String
            Get
                Return ResourceManager.GetString("GS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Guatemala ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property GT() As String
            Get
                Return ResourceManager.GetString("GT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Guam ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property GU() As String
            Get
                Return ResourceManager.GetString("GU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Guinea Bissau ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property GW() As String
            Get
                Return ResourceManager.GetString("GW", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Guyana ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property GY() As String
            Get
                Return ResourceManager.GetString("GY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Hong Kong ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property HK() As String
            Get
                Return ResourceManager.GetString("HK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Heard und McDonald Islands ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property HM() As String
            Get
                Return ResourceManager.GetString("HM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Honduras ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property HN() As String
            Get
                Return ResourceManager.GetString("HN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Kroatien ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property HR() As String
            Get
                Return ResourceManager.GetString("HR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Haiti ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property HT() As String
            Get
                Return ResourceManager.GetString("HT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Ungarn ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property HU() As String
            Get
                Return ResourceManager.GetString("HU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Indonesien ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ID() As String
            Get
                Return ResourceManager.GetString("ID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Irland ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property IE() As String
            Get
                Return ResourceManager.GetString("IE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Israel ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property IL() As String
            Get
                Return ResourceManager.GetString("IL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Isle of Man ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property IM() As String
            Get
                Return ResourceManager.GetString("IM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Britisch-Indischer Ozean ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property IO() As String
            Get
                Return ResourceManager.GetString("IO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Irak ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property IQ() As String
            Get
                Return ResourceManager.GetString("IQ", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Iran ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property IR() As String
            Get
                Return ResourceManager.GetString("IR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Italien ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property IT() As String
            Get
                Return ResourceManager.GetString("IT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Jersey ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property JE() As String
            Get
                Return ResourceManager.GetString("JE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Jamaika ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property JM() As String
            Get
                Return ResourceManager.GetString("JM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Jordanien ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property JO() As String
            Get
                Return ResourceManager.GetString("JO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Japan ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property JP() As String
            Get
                Return ResourceManager.GetString("JP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Kenia ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property KE() As String
            Get
                Return ResourceManager.GetString("KE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Kirgisistan ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property KG() As String
            Get
                Return ResourceManager.GetString("KG", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Kambodscha ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property KH() As String
            Get
                Return ResourceManager.GetString("KH", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Kiribati ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property KI() As String
            Get
                Return ResourceManager.GetString("KI", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Komoren ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property KM() As String
            Get
                Return ResourceManager.GetString("KM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die St. Kitts Nevis Anguilla ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property KN() As String
            Get
                Return ResourceManager.GetString("KN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Nord Korea ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property KP() As String
            Get
                Return ResourceManager.GetString("KP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Süd Korea ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property KS() As String
            Get
                Return ResourceManager.GetString("KS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Kuwait ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property KW() As String
            Get
                Return ResourceManager.GetString("KW", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Kaiman Inseln ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property KY() As String
            Get
                Return ResourceManager.GetString("KY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Kasachstan ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property KZ() As String
            Get
                Return ResourceManager.GetString("KZ", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Laos ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property LA() As String
            Get
                Return ResourceManager.GetString("LA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Libanon ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property LB() As String
            Get
                Return ResourceManager.GetString("LB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Saint Lucia ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property LC() As String
            Get
                Return ResourceManager.GetString("LC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Liechtenstein ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property LI() As String
            Get
                Return ResourceManager.GetString("LI", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Sri Lanka ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property LK() As String
            Get
                Return ResourceManager.GetString("LK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Liberia ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property LR() As String
            Get
                Return ResourceManager.GetString("LR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Lesotho ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property LS() As String
            Get
                Return ResourceManager.GetString("LS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Lithauen ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property LT() As String
            Get
                Return ResourceManager.GetString("LT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Luxenburg ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property LU() As String
            Get
                Return ResourceManager.GetString("LU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Lettland ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property LV() As String
            Get
                Return ResourceManager.GetString("LV", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Libyen ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property LY() As String
            Get
                Return ResourceManager.GetString("LY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Marokko ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MA() As String
            Get
                Return ResourceManager.GetString("MA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Monaco ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MC() As String
            Get
                Return ResourceManager.GetString("MC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Moldavien ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MD() As String
            Get
                Return ResourceManager.GetString("MD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Madagaskar ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MG() As String
            Get
                Return ResourceManager.GetString("MG", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Marshall Inseln ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MH() As String
            Get
                Return ResourceManager.GetString("MH", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Mazedonien ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MK() As String
            Get
                Return ResourceManager.GetString("MK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Mali ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ML() As String
            Get
                Return ResourceManager.GetString("ML", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Birma ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MM() As String
            Get
                Return ResourceManager.GetString("MM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Mongolei ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MN() As String
            Get
                Return ResourceManager.GetString("MN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Macau ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MO() As String
            Get
                Return ResourceManager.GetString("MO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Marianen ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MP() As String
            Get
                Return ResourceManager.GetString("MP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Martinique ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MQ() As String
            Get
                Return ResourceManager.GetString("MQ", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Mauretanien ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MR() As String
            Get
                Return ResourceManager.GetString("MR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Montserrat ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MS() As String
            Get
                Return ResourceManager.GetString("MS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Malta ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MT() As String
            Get
                Return ResourceManager.GetString("MT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Mauritius ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MU() As String
            Get
                Return ResourceManager.GetString("MU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Malediven ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MV() As String
            Get
                Return ResourceManager.GetString("MV", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Malawi ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MW() As String
            Get
                Return ResourceManager.GetString("MW", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Mexiko ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MX() As String
            Get
                Return ResourceManager.GetString("MX", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Malaysia ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MY() As String
            Get
                Return ResourceManager.GetString("MY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Mocambique ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MZ() As String
            Get
                Return ResourceManager.GetString("MZ", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Namibia ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property NA() As String
            Get
                Return ResourceManager.GetString("NA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Neukaledonien ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property NC() As String
            Get
                Return ResourceManager.GetString("NC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Niger ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property NE() As String
            Get
                Return ResourceManager.GetString("NE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Norfolk Inseln ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property NF() As String
            Get
                Return ResourceManager.GetString("NF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Nigeria ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property NG() As String
            Get
                Return ResourceManager.GetString("NG", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Nicaragua ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property NI() As String
            Get
                Return ResourceManager.GetString("NI", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Niederlande ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property NL() As String
            Get
                Return ResourceManager.GetString("NL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Norwegen ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property NO() As String
            Get
                Return ResourceManager.GetString("NO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Nepal ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property NP() As String
            Get
                Return ResourceManager.GetString("NP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Nauru ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property NR() As String
            Get
                Return ResourceManager.GetString("NR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Niue ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property NU() As String
            Get
                Return ResourceManager.GetString("NU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Neuseeland ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property NZ() As String
            Get
                Return ResourceManager.GetString("NZ", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Oman ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property OM() As String
            Get
                Return ResourceManager.GetString("OM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Panama ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property PA() As String
            Get
                Return ResourceManager.GetString("PA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Peru ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property PE() As String
            Get
                Return ResourceManager.GetString("PE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Französisch Polynesien ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property PF() As String
            Get
                Return ResourceManager.GetString("PF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Papua Neuguinea ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property PG() As String
            Get
                Return ResourceManager.GetString("PG", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Philippinen ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property PH() As String
            Get
                Return ResourceManager.GetString("PH", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Pakistan ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property PK() As String
            Get
                Return ResourceManager.GetString("PK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Polen ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property PL() As String
            Get
                Return ResourceManager.GetString("PL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die St. Pierre und Miquelon ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property PM() As String
            Get
                Return ResourceManager.GetString("PM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Pitcairn ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property PN() As String
            Get
                Return ResourceManager.GetString("PN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Puerto Rico ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property PR() As String
            Get
                Return ResourceManager.GetString("PR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Palästina ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property PS() As String
            Get
                Return ResourceManager.GetString("PS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Portugal ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property PT() As String
            Get
                Return ResourceManager.GetString("PT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Palau ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property PW() As String
            Get
                Return ResourceManager.GetString("PW", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Paraguay ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property PY() As String
            Get
                Return ResourceManager.GetString("PY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Qatar ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property QA() As String
            Get
                Return ResourceManager.GetString("QA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Reunion ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property RE() As String
            Get
                Return ResourceManager.GetString("RE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Rumänien ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property RO() As String
            Get
                Return ResourceManager.GetString("RO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Serbien ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property RS() As String
            Get
                Return ResourceManager.GetString("RS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Rußland ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property RU() As String
            Get
                Return ResourceManager.GetString("RU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Ruanda ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property RW() As String
            Get
                Return ResourceManager.GetString("RW", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Saudi Arabien ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property SA() As String
            Get
                Return ResourceManager.GetString("SA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Solomon Inseln ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property SB() As String
            Get
                Return ResourceManager.GetString("SB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Seychellen ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property SC() As String
            Get
                Return ResourceManager.GetString("SC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Sudan ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property SD() As String
            Get
                Return ResourceManager.GetString("SD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Schweden ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property SE() As String
            Get
                Return ResourceManager.GetString("SE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Singapur ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property SG() As String
            Get
                Return ResourceManager.GetString("SG", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die St. Helena ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property SH() As String
            Get
                Return ResourceManager.GetString("SH", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Slowenien ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property SI() As String
            Get
                Return ResourceManager.GetString("SI", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Svalbard und Jan Mayen Islands ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property SJ() As String
            Get
                Return ResourceManager.GetString("SJ", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Slowakei -slowakische Republik- ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property SK() As String
            Get
                Return ResourceManager.GetString("SK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Sierra Leone ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property SL() As String
            Get
                Return ResourceManager.GetString("SL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die San Marino ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property SM() As String
            Get
                Return ResourceManager.GetString("SM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Senegal ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property SN() As String
            Get
                Return ResourceManager.GetString("SN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Somalia ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property SO() As String
            Get
                Return ResourceManager.GetString("SO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Surinam ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property SR() As String
            Get
                Return ResourceManager.GetString("SR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Sao Tome ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ST() As String
            Get
                Return ResourceManager.GetString("ST", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die El Salvador ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property SV() As String
            Get
                Return ResourceManager.GetString("SV", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die St. Martin ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property SX() As String
            Get
                Return ResourceManager.GetString("SX", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Syrien ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property SY() As String
            Get
                Return ResourceManager.GetString("SY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Swasiland ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property SZ() As String
            Get
                Return ResourceManager.GetString("SZ", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Turks und Kaikos Inseln ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property TC() As String
            Get
                Return ResourceManager.GetString("TC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Tschad ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property TD() As String
            Get
                Return ResourceManager.GetString("TD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Französisches Süd-Territorium ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property TF() As String
            Get
                Return ResourceManager.GetString("TF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Togo ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property TG() As String
            Get
                Return ResourceManager.GetString("TG", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Thailand ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property TH() As String
            Get
                Return ResourceManager.GetString("TH", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Tadschikistan ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property TJ() As String
            Get
                Return ResourceManager.GetString("TJ", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Tokelau ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property TK() As String
            Get
                Return ResourceManager.GetString("TK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Turkmenistan ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property TM() As String
            Get
                Return ResourceManager.GetString("TM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Tunesien ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property TN() As String
            Get
                Return ResourceManager.GetString("TN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Timor ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property TP() As String
            Get
                Return ResourceManager.GetString("TP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Türkei ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property TR() As String
            Get
                Return ResourceManager.GetString("TR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Trinidad Tobago ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property TT() As String
            Get
                Return ResourceManager.GetString("TT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Tuvalu ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property TV() As String
            Get
                Return ResourceManager.GetString("TV", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Taiwan ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property TW() As String
            Get
                Return ResourceManager.GetString("TW", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Tansania ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property TZ() As String
            Get
                Return ResourceManager.GetString("TZ", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Ukraine ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property UA() As String
            Get
                Return ResourceManager.GetString("UA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Uganda ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property UG() As String
            Get
                Return ResourceManager.GetString("UG", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Großbritannien(UK) ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property UK() As String
            Get
                Return ResourceManager.GetString("UK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Vereinigte Staaten von Amerika ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property US() As String
            Get
                Return ResourceManager.GetString("US", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Uruguay ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property UY() As String
            Get
                Return ResourceManager.GetString("UY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Usbekistan ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property UZ() As String
            Get
                Return ResourceManager.GetString("UZ", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Vatikan ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property VA() As String
            Get
                Return ResourceManager.GetString("VA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die St. Vincent ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property VC() As String
            Get
                Return ResourceManager.GetString("VC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Venezuela ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property VE() As String
            Get
                Return ResourceManager.GetString("VE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Virgin Island (Brit.) ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property VG() As String
            Get
                Return ResourceManager.GetString("VG", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Virgin Island (USA) ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property VI() As String
            Get
                Return ResourceManager.GetString("VI", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Vietnam ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property VN() As String
            Get
                Return ResourceManager.GetString("VN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Vanuatu ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property VU() As String
            Get
                Return ResourceManager.GetString("VU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Wallis et Futuna ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property WF() As String
            Get
                Return ResourceManager.GetString("WF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Samoa ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property WS() As String
            Get
                Return ResourceManager.GetString("WS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Jemen ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property YE() As String
            Get
                Return ResourceManager.GetString("YE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Mayotte ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property YT() As String
            Get
                Return ResourceManager.GetString("YT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Südafrika ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ZA() As String
            Get
                Return ResourceManager.GetString("ZA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Sambia ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ZM() As String
            Get
                Return ResourceManager.GetString("ZM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Zimbabwe ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ZW() As String
            Get
                Return ResourceManager.GetString("ZW", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
