'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace Localize
    
    'Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    '-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    'Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    'mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    '''<summary>
    '''  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Public Class resCommon
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("FBoxDial.resCommon", GetType(resCommon).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        '''  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Anrufmonitor ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strAnrMon() As String
            Get
                Return ResourceManager.GetString("strAnrMon", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Abbrechen ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strCancel() As String
            Get
                Return ResourceManager.GetString("strCancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Abbrechen geklickt ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strCancelClicked() As String
            Get
                Return ResourceManager.GetString("strCancelClicked", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Alle auswählen ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strCheckAll() As String
            Get
                Return ResourceManager.GetString("strCheckAll", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Einstellungen ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strConfig() As String
            Get
                Return ResourceManager.GetString("strConfig", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Datum ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strDate() As String
            Get
                Return ResourceManager.GetString("strDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Gerät ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strDevice() As String
            Get
                Return ResourceManager.GetString("strDevice", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Wählhilfe ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strDialer() As String
            Get
                Return ResourceManager.GetString("strDialer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Dauer ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strDuration() As String
            Get
                Return ResourceManager.GetString("strDuration", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Endzeit ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strEndTime() As String
            Get
                Return ResourceManager.GetString("strEndTime", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Import der Anrufliste ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strImportCallerList() As String
            Get
                Return ResourceManager.GetString("strImportCallerList", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Eingene Nr. ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strMyNumber() As String
            Get
                Return ResourceManager.GetString("strMyNumber", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strName() As String
            Get
                Return ResourceManager.GetString("strName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Keine Einträge markiert ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strNoEntriesSelected() As String
            Get
                Return ResourceManager.GetString("strNoEntriesSelected", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Grundeinstellung ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strOptBaseConfig() As String
            Get
                Return ResourceManager.GetString("strOptBaseConfig", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Kontakterstellung ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strOptCreateContact() As String
            Get
                Return ResourceManager.GetString("strOptCreateContact", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Info ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strOptInfo() As String
            Get
                Return ResourceManager.GetString("strOptInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Journal ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strOptJournal() As String
            Get
                Return ResourceManager.GetString("strOptJournal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die MicroSIP ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strOptMicroSIP() As String
            Get
                Return ResourceManager.GetString("strOptMicroSIP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Telefone ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strOptPhone() As String
            Get
                Return ResourceManager.GetString("strOptPhone", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Phoner ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strOptPhoner() As String
            Get
                Return ResourceManager.GetString("strOptPhoner", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Kontaktsuche ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strOptSearchContact() As String
            Get
                Return ResourceManager.GetString("strOptSearchContact", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Port ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strPort() As String
            Get
                Return ResourceManager.GetString("strPort", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Gegenstelle ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strRemoteCaller() As String
            Get
                Return ResourceManager.GetString("strRemoteCaller", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Starte Jounalimport ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strStartJounalImport() As String
            Get
                Return ResourceManager.GetString("strStartJounalImport", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Startzeit ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strStartTime() As String
            Get
                Return ResourceManager.GetString("strStartTime", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Status ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strStatus() As String
            Get
                Return ResourceManager.GetString("strStatus", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Keine auswählen ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strUncheckAll() As String
            Get
                Return ResourceManager.GetString("strUncheckAll", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
