'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace Localize
    
    'Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    '-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    'Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    'mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    '''<summary>
    '''  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Public Class resCommon
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("FBoxDial.resCommon", GetType(resCommon).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        '''  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Termineintrag konnte nicht erstellt werden. ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strAppointmentError() As String
            Get
                Return ResourceManager.GetString("strAppointmentError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Anruferinnerung:  ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strAppointmentSubject() As String
            Get
                Return ResourceManager.GetString("strAppointmentSubject", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Land ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strArea() As String
            Get
                Return ResourceManager.GetString("strArea", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Rufsperre ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strCallBarring() As String
            Get
                Return ResourceManager.GetString("strCallBarring", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Erstellt durch das {0} am {1}: {2}{3}  ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strCreateContact() As String
            Get
                Return ResourceManager.GetString("strCreateContact", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Datum ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strDate() As String
            Get
                Return ResourceManager.GetString("strDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Fehler in Funktion &apos;{0}&apos;: {1} ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strErrorMsgBox() As String
            Get
                Return ResourceManager.GetString("strErrorMsgBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die 2-Faktor-Authentisierung der Fritz!Box ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strHead2FA() As String
            Get
                Return ResourceManager.GetString("strHead2FA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Ort ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strLocation() As String
            Get
                Return ResourceManager.GetString("strLocation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Ohne Name ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strOhneName() As String
            Get
                Return ResourceManager.GetString("strOhneName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die 2-Faktor-Authentisierung ist erforderlich: {0} ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strQuestion2FA() As String
            Get
                Return ResourceManager.GetString("strQuestion2FA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Nummer ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTelNr() As String
            Get
                Return ResourceManager.GetString("strTelNr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Zeit ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strTime() As String
            Get
                Return ResourceManager.GetString("strTime", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Es wurde keine Zahl eingegeben oder &apos;{0}&apos; ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strValidationIntChr() As String
            Get
                Return ResourceManager.GetString("strValidationIntChr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Der eingegebene Wert ist größer als der Maximalwert von {0} ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strValidationIntLarger() As String
            Get
                Return ResourceManager.GetString("strValidationIntLarger", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Der eingegebene Wert ist kleiner als der Mindestwert von {0} ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strValidationIntLess() As String
            Get
                Return ResourceManager.GetString("strValidationIntLess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Der Wert muss im Bereich zwischen {0} und {1} liegen. ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strValidationIntRange() As String
            Get
                Return ResourceManager.GetString("strValidationIntRange", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
