'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
'-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
'Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
'mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
'''<summary>
'''  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
Public Class resEnum
    
    Private Shared resourceMan As Global.System.Resources.ResourceManager
    
    Private Shared resourceCulture As Global.System.Globalization.CultureInfo
    
    <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
    Friend Sub New()
        MyBase.New
    End Sub
    
    '''<summary>
    '''  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("FBoxDial.resEnum", GetType(resEnum).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property
    
    '''<summary>
    '''  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
    '''  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Public Shared Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set
            resourceCulture = value
        End Set
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Privat ähnelt.
    '''</summary>
    Public Shared ReadOnly Property _private() As String
        Get
            Return ResourceManager.GetString("private", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Assistent ähnelt.
    '''</summary>
    Public Shared ReadOnly Property AssistantTelephoneNumber() As String
        Get
            Return ResourceManager.GetString("AssistantTelephoneNumber", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Geschäftlich 2 ähnelt.
    '''</summary>
    Public Shared ReadOnly Property Business2TelephoneNumber() As String
        Get
            Return ResourceManager.GetString("Business2TelephoneNumber", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Fax geschäftlich ähnelt.
    '''</summary>
    Public Shared ReadOnly Property BusinessFaxNumber() As String
        Get
            Return ResourceManager.GetString("BusinessFaxNumber", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Geschäftlich ähnelt.
    '''</summary>
    Public Shared ReadOnly Property BusinessTelephoneNumber() As String
        Get
            Return ResourceManager.GetString("BusinessTelephoneNumber", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Rückmeldung ähnelt.
    '''</summary>
    Public Shared ReadOnly Property CallbackTelephoneNumber() As String
        Get
            Return ResourceManager.GetString("CallbackTelephoneNumber", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Auto ähnelt.
    '''</summary>
    Public Shared ReadOnly Property CarTelephoneNumber() As String
        Get
            Return ResourceManager.GetString("CarTelephoneNumber", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Firma ähnelt.
    '''</summary>
    Public Shared ReadOnly Property CompanyMainTelephoneNumber() As String
        Get
            Return ResourceManager.GetString("CompanyMainTelephoneNumber", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Fax ähnelt.
    '''</summary>
    Public Shared ReadOnly Property fax_work() As String
        Get
            Return ResourceManager.GetString("fax_work", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Privat ähnelt.
    '''</summary>
    Public Shared ReadOnly Property home() As String
        Get
            Return ResourceManager.GetString("home", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Privat 2 ähnelt.
    '''</summary>
    Public Shared ReadOnly Property Home2TelephoneNumber() As String
        Get
            Return ResourceManager.GetString("Home2TelephoneNumber", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Fax privat ähnelt.
    '''</summary>
    Public Shared ReadOnly Property HomeFaxNumber() As String
        Get
            Return ResourceManager.GetString("HomeFaxNumber", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Privat ähnelt.
    '''</summary>
    Public Shared ReadOnly Property HomeTelephoneNumber() As String
        Get
            Return ResourceManager.GetString("HomeTelephoneNumber", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Intern ähnelt.
    '''</summary>
    Public Shared ReadOnly Property intern() As String
        Get
            Return ResourceManager.GetString("intern", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die ISDN ähnelt.
    '''</summary>
    Public Shared ReadOnly Property ISDNNumber() As String
        Get
            Return ResourceManager.GetString("ISDNNumber", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Anrufbeantworter ähnelt.
    '''</summary>
    Public Shared ReadOnly Property memo() As String
        Get
            Return ResourceManager.GetString("memo", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Mobil ähnelt.
    '''</summary>
    Public Shared ReadOnly Property mobile() As String
        Get
            Return ResourceManager.GetString("mobile", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Mobiltelefon ähnelt.
    '''</summary>
    Public Shared ReadOnly Property MobileTelephoneNumber() As String
        Get
            Return ResourceManager.GetString("MobileTelephoneNumber", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Sonstige ähnelt.
    '''</summary>
    Public Shared ReadOnly Property notset() As String
        Get
            Return ResourceManager.GetString("notset", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Sonstige ähnelt.
    '''</summary>
    Public Shared ReadOnly Property other() As String
        Get
            Return ResourceManager.GetString("other", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Weiteres Fax ähnelt.
    '''</summary>
    Public Shared ReadOnly Property OtherFaxNumber() As String
        Get
            Return ResourceManager.GetString("OtherFaxNumber", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Weitere ähnelt.
    '''</summary>
    Public Shared ReadOnly Property OtherTelephoneNumber() As String
        Get
            Return ResourceManager.GetString("OtherTelephoneNumber", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Pager ähnelt.
    '''</summary>
    Public Shared ReadOnly Property PagerNumber() As String
        Get
            Return ResourceManager.GetString("PagerNumber", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Haupttelefon ähnelt.
    '''</summary>
    Public Shared ReadOnly Property PrimaryTelephoneNumber() As String
        Get
            Return ResourceManager.GetString("PrimaryTelephoneNumber", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Funkruf ähnelt.
    '''</summary>
    Public Shared ReadOnly Property RadioTelephoneNumber() As String
        Get
            Return ResourceManager.GetString("RadioTelephoneNumber", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Telex ähnelt.
    '''</summary>
    Public Shared ReadOnly Property TelexNumber() As String
        Get
            Return ResourceManager.GetString("TelexNumber", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Texttelefon ähnelt.
    '''</summary>
    Public Shared ReadOnly Property TTYTDDTelephoneNumber() As String
        Get
            Return ResourceManager.GetString("TTYTDDTelephoneNumber", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Arbeit ähnelt.
    '''</summary>
    Public Shared ReadOnly Property work() As String
        Get
            Return ResourceManager.GetString("work", resourceCulture)
        End Get
    End Property
End Class
