'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
'-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
'Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
'mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
'''<summary>
'''  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
Public Class resEnum
    
    Private Shared resourceMan As Global.System.Resources.ResourceManager
    
    Private Shared resourceCulture As Global.System.Globalization.CultureInfo
    
    <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
    Friend Sub New()
        MyBase.New
    End Sub
    
    '''<summary>
    '''  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("FBoxDial.resEnum", GetType(resEnum).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property
    
    '''<summary>
    '''  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
    '''  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Public Shared Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set
            resourceCulture = value
        End Set
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Privat ähnelt.
    '''</summary>
    Public Shared ReadOnly Property _private() As String
        Get
            Return ResourceManager.GetString("private", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Assistent ähnelt.
    '''</summary>
    Public Shared ReadOnly Property AssistantTelephoneNumber() As String
        Get
            Return ResourceManager.GetString("AssistantTelephoneNumber", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Umleitung bei Klingelsperre ähnelt.
    '''</summary>
    Public Shared ReadOnly Property BellBlockade() As String
        Get
            Return ResourceManager.GetString("BellBlockade", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Geschäftlich 2 ähnelt.
    '''</summary>
    Public Shared ReadOnly Property Business2TelephoneNumber() As String
        Get
            Return ResourceManager.GetString("Business2TelephoneNumber", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Fax geschäftlich ähnelt.
    '''</summary>
    Public Shared ReadOnly Property BusinessFaxNumber() As String
        Get
            Return ResourceManager.GetString("BusinessFaxNumber", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Geschäftlich ähnelt.
    '''</summary>
    Public Shared ReadOnly Property BusinessTelephoneNumber() As String
        Get
            Return ResourceManager.GetString("BusinessTelephoneNumber", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die bei Besetzt ähnelt.
    '''</summary>
    Public Shared ReadOnly Property Busy() As String
        Get
            Return ResourceManager.GetString("Busy", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Rückmeldung ähnelt.
    '''</summary>
    Public Shared ReadOnly Property CallbackTelephoneNumber() As String
        Get
            Return ResourceManager.GetString("CallbackTelephoneNumber", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Auto ähnelt.
    '''</summary>
    Public Shared ReadOnly Property CarTelephoneNumber() As String
        Get
            Return ResourceManager.GetString("CarTelephoneNumber", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Firma ähnelt.
    '''</summary>
    Public Shared ReadOnly Property CompanyMainTelephoneNumber() As String
        Get
            Return ResourceManager.GetString("CompanyMainTelephoneNumber", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Verzögert ähnelt.
    '''</summary>
    Public Shared ReadOnly Property Delayed() As String
        Get
            Return ResourceManager.GetString("Delayed", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Verzögert oder bei Besetzt ähnelt.
    '''</summary>
    Public Shared ReadOnly Property DelayedOrBusy() As String
        Get
            Return ResourceManager.GetString("DelayedOrBusy", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Dunkel ähnelt.
    '''</summary>
    Public Shared ReadOnly Property DesignDark() As String
        Get
            Return ResourceManager.GetString("DesignDark", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Hell ähnelt.
    '''</summary>
    Public Shared ReadOnly Property DesignLight() As String
        Get
            Return ResourceManager.GetString("DesignLight", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Office Thema ähnelt.
    '''</summary>
    Public Shared ReadOnly Property DesignOffice() As String
        Get
            Return ResourceManager.GetString("DesignOffice", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Direkter Anruf ähnelt.
    '''</summary>
    Public Shared ReadOnly Property DirectCall() As String
        Get
            Return ResourceManager.GetString("DirectCall", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Alle ähnelt.
    '''</summary>
    Public Shared ReadOnly Property eAllCalls() As String
        Get
            Return ResourceManager.GetString("eAllCalls", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die GSM ähnelt.
    '''</summary>
    Public Shared ReadOnly Property eGSM() As String
        Get
            Return ResourceManager.GetString("eGSM", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die ISDN ähnelt.
    '''</summary>
    Public Shared ReadOnly Property eISDN() As String
        Get
            Return ResourceManager.GetString("eISDN", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Keine ähnelt.
    '''</summary>
    Public Shared ReadOnly Property eNone() As String
        Get
            Return ResourceManager.GetString("eNone", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die POTS ähnelt.
    '''</summary>
    Public Shared ReadOnly Property ePOTS() As String
        Get
            Return ResourceManager.GetString("ePOTS", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die VoIP ähnelt.
    '''</summary>
    Public Shared ReadOnly Property eVoIP() As String
        Get
            Return ResourceManager.GetString("eVoIP", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Fax ähnelt.
    '''</summary>
    Public Shared ReadOnly Property fax_work() As String
        Get
            Return ResourceManager.GetString("fax_work", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die FON1 ähnelt.
    '''</summary>
    Public Shared ReadOnly Property fon1() As String
        Get
            Return ResourceManager.GetString("fon1", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die FON2 ähnelt.
    '''</summary>
    Public Shared ReadOnly Property fon2() As String
        Get
            Return ResourceManager.GetString("fon2", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die FON3 ähnelt.
    '''</summary>
    Public Shared ReadOnly Property fon3() As String
        Get
            Return ResourceManager.GetString("fon3", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die FON4 ähnelt.
    '''</summary>
    Public Shared ReadOnly Property fon4() As String
        Get
            Return ResourceManager.GetString("fon4", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die alle Anrufe ähnelt.
    '''</summary>
    Public Shared ReadOnly Property fromAll() As String
        Get
            Return ResourceManager.GetString("fromAll", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die von Anonym ähnelt.
    '''</summary>
    Public Shared ReadOnly Property fromAnonymous() As String
        Get
            Return ResourceManager.GetString("fromAnonymous", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die von Person nicht im Telefonbuch ähnelt.
    '''</summary>
    Public Shared ReadOnly Property fromNotInPhonebook() As String
        Get
            Return ResourceManager.GetString("fromNotInPhonebook", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die von kein-VIP ähnelt.
    '''</summary>
    Public Shared ReadOnly Property fromNotVIP() As String
        Get
            Return ResourceManager.GetString("fromNotVIP", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die von Rufnummer ähnelt.
    '''</summary>
    Public Shared ReadOnly Property fromNumber() As String
        Get
            Return ResourceManager.GetString("fromNumber", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die von Person im Telefonbuch ähnelt.
    '''</summary>
    Public Shared ReadOnly Property fromPB() As String
        Get
            Return ResourceManager.GetString("fromPB", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die von VIP ähnelt.
    '''</summary>
    Public Shared ReadOnly Property fromVIP() As String
        Get
            Return ResourceManager.GetString("fromVIP", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Privat ähnelt.
    '''</summary>
    Public Shared ReadOnly Property home() As String
        Get
            Return ResourceManager.GetString("home", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Privat 2 ähnelt.
    '''</summary>
    Public Shared ReadOnly Property Home2TelephoneNumber() As String
        Get
            Return ResourceManager.GetString("Home2TelephoneNumber", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Fax privat ähnelt.
    '''</summary>
    Public Shared ReadOnly Property HomeFaxNumber() As String
        Get
            Return ResourceManager.GetString("HomeFaxNumber", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Privat ähnelt.
    '''</summary>
    Public Shared ReadOnly Property HomeTelephoneNumber() As String
        Get
            Return ResourceManager.GetString("HomeTelephoneNumber", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Sofort ähnelt.
    '''</summary>
    Public Shared ReadOnly Property Immediately() As String
        Get
            Return ResourceManager.GetString("Immediately", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Intern ähnelt.
    '''</summary>
    Public Shared ReadOnly Property intern() As String
        Get
            Return ResourceManager.GetString("intern", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Softphone: MicroSIP ähnelt.
    '''</summary>
    Public Shared ReadOnly Property IPConnMicroSIP() As String
        Get
            Return ResourceManager.GetString("IPConnMicroSIP", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Keine ähnelt.
    '''</summary>
    Public Shared ReadOnly Property IPConnNone() As String
        Get
            Return ResourceManager.GetString("IPConnNone", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Softphone: Phoner ähnelt.
    '''</summary>
    Public Shared ReadOnly Property IPConnPhoner() As String
        Get
            Return ResourceManager.GetString("IPConnPhoner", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die http Anfrage ähnelt.
    '''</summary>
    Public Shared ReadOnly Property IPConnURI() As String
        Get
            Return ResourceManager.GetString("IPConnURI", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Snom (Digest) ähnelt.
    '''</summary>
    Public Shared ReadOnly Property IPPhoneAuthSnom() As String
        Get
            Return ResourceManager.GetString("IPPhoneAuthSnom", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die ISDN ähnelt.
    '''</summary>
    Public Shared ReadOnly Property ISDNNumber() As String
        Get
            Return ResourceManager.GetString("ISDNNumber", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Verzögert lang ähnelt.
    '''</summary>
    Public Shared ReadOnly Property LongDelayed() As String
        Get
            Return ResourceManager.GetString("LongDelayed", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Anrufbeantworter ähnelt.
    '''</summary>
    Public Shared ReadOnly Property memo() As String
        Get
            Return ResourceManager.GetString("memo", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Mobil ähnelt.
    '''</summary>
    Public Shared ReadOnly Property mobile() As String
        Get
            Return ResourceManager.GetString("mobile", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Mobiltelefon ähnelt.
    '''</summary>
    Public Shared ReadOnly Property MobileTelephoneNumber() As String
        Get
            Return ResourceManager.GetString("MobileTelephoneNumber", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Keine Signalisierung ähnelt.
    '''</summary>
    Public Shared ReadOnly Property NoSignal() As String
        Get
            Return ResourceManager.GetString("NoSignal", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die (nicht gesetzt) ähnelt.
    '''</summary>
    Public Shared ReadOnly Property notset() As String
        Get
            Return ResourceManager.GetString("notset", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Umleitung ausgeschaltet ähnelt.
    '''</summary>
    Public Shared ReadOnly Property Off() As String
        Get
            Return ResourceManager.GetString("Off", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Sonstige ähnelt.
    '''</summary>
    Public Shared ReadOnly Property other() As String
        Get
            Return ResourceManager.GetString("other", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Weiteres Fax ähnelt.
    '''</summary>
    Public Shared ReadOnly Property OtherFaxNumber() As String
        Get
            Return ResourceManager.GetString("OtherFaxNumber", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Weitere ähnelt.
    '''</summary>
    Public Shared ReadOnly Property OtherTelephoneNumber() As String
        Get
            Return ResourceManager.GetString("OtherTelephoneNumber", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Pager ähnelt.
    '''</summary>
    Public Shared ReadOnly Property PagerNumber() As String
        Get
            Return ResourceManager.GetString("PagerNumber", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Parallelruf ähnelt.
    '''</summary>
    Public Shared ReadOnly Property ParallelCall() As String
        Get
            Return ResourceManager.GetString("ParallelCall", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Haupttelefon ähnelt.
    '''</summary>
    Public Shared ReadOnly Property PrimaryTelephoneNumber() As String
        Get
            Return ResourceManager.GetString("PrimaryTelephoneNumber", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Funkruf ähnelt.
    '''</summary>
    Public Shared ReadOnly Property RadioTelephoneNumber() As String
        Get
            Return ResourceManager.GetString("RadioTelephoneNumber", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Verzögert kurz ähnelt.
    '''</summary>
    Public Shared ReadOnly Property ShortDelayed() As String
        Get
            Return ResourceManager.GetString("ShortDelayed", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Telex ähnelt.
    '''</summary>
    Public Shared ReadOnly Property Telex() As String
        Get
            Return ResourceManager.GetString("Telex", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Telex ähnelt.
    '''</summary>
    Public Shared ReadOnly Property TelexNumber() As String
        Get
            Return ResourceManager.GetString("TelexNumber", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die an ? ähnelt.
    '''</summary>
    Public Shared ReadOnly Property toAny() As String
        Get
            Return ResourceManager.GetString("toAny", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die an MSN ähnelt.
    '''</summary>
    Public Shared ReadOnly Property toMSN() As String
        Get
            Return ResourceManager.GetString("toMSN", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die an Festnetz ähnelt.
    '''</summary>
    Public Shared ReadOnly Property toPOTS() As String
        Get
            Return ResourceManager.GetString("toPOTS", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die an VOIP ähnelt.
    '''</summary>
    Public Shared ReadOnly Property toVoIP() As String
        Get
            Return ResourceManager.GetString("toVoIP", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Texttelefon ähnelt.
    '''</summary>
    Public Shared ReadOnly Property TTYTDDTelephoneNumber() As String
        Get
            Return ResourceManager.GetString("TTYTDDTelephoneNumber", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Unbekannt ähnelt.
    '''</summary>
    Public Shared ReadOnly Property Unknown() As String
        Get
            Return ResourceManager.GetString("Unknown", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die VIP ähnelt.
    '''</summary>
    Public Shared ReadOnly Property VIP() As String
        Get
            Return ResourceManager.GetString("VIP", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Arbeit ähnelt.
    '''</summary>
    Public Shared ReadOnly Property work() As String
        Get
            Return ResourceManager.GetString("work", resourceCulture)
        End Get
    End Property
End Class
