'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
'-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
'Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
'mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
'''<summary>
'''  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
Public Class resImageMso
    
    Private Shared resourceMan As Global.System.Resources.ResourceManager
    
    Private Shared resourceCulture As Global.System.Globalization.CultureInfo
    
    <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
    Friend Sub New()
        MyBase.New
    End Sub
    
    '''<summary>
    '''  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("FBoxDial.resImageMso", GetType(resImageMso).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property
    
    '''<summary>
    '''  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
    '''  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Public Shared Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set
            resourceCulture = value
        End Set
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die ShapeStar ähnelt.
    '''</summary>
    Public Shared ReadOnly Property AddVIP_ImageMso() As String
        Get
            Return ResourceManager.GetString("AddVIP_ImageMso", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
    '''</summary>
    Public Shared ReadOnly Property Config_ImageMso() As String
        Get
            Return ResourceManager.GetString("Config_ImageMso", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die RecordsSaveAsOutlookContact ähnelt.
    '''</summary>
    Public Shared ReadOnly Property CreateContact_ImageMso() As String
        Get
            Return ResourceManager.GetString("CreateContact_ImageMso", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die AutoDial ähnelt.
    '''</summary>
    Public Shared ReadOnly Property Dial_ImageMso() As String
        Get
            Return ResourceManager.GetString("Dial_ImageMso", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die SlidesPerPage9Slides ähnelt.
    '''</summary>
    Public Shared ReadOnly Property DirectCall_ImageMso() As String
        Get
            Return ResourceManager.GetString("DirectCall_ImageMso", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die ToolDelete ähnelt.
    '''</summary>
    Public Shared ReadOnly Property DynListDel_ImageMso() As String
        Get
            Return ResourceManager.GetString("DynListDel_ImageMso", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die NewJournalEntry ähnelt.
    '''</summary>
    Public Shared ReadOnly Property JournalImport_ImageMso() As String
        Get
            Return ResourceManager.GetString("JournalImport_ImageMso", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die HighImportance ähnelt.
    '''</summary>
    Public Shared ReadOnly Property ListCRV_ImageMso() As String
        Get
            Return ResourceManager.GetString("ListCRV_ImageMso", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die ShowNotesPage ähnelt.
    '''</summary>
    Public Shared ReadOnly Property Note_ImageMso() As String
        Get
            Return ResourceManager.GetString("Note_ImageMso", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die PersonaStatusOffline ähnelt.
    '''</summary>
    Public Shared ReadOnly Property OfflineCallMonitor_ImageMso() As String
        Get
            Return ResourceManager.GetString("OfflineCallMonitor_ImageMso", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die PersonaStatusOnline ähnelt.
    '''</summary>
    Public Shared ReadOnly Property OnlineCallMonitor_ImageMso() As String
        Get
            Return ResourceManager.GetString("OnlineCallMonitor_ImageMso", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die AddressBook ähnelt.
    '''</summary>
    Public Shared ReadOnly Property PhoneBooks_ImageMso() As String
        Get
            Return ResourceManager.GetString("PhoneBooks_ImageMso", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die DirectRepliesTo ähnelt.
    '''</summary>
    Public Shared ReadOnly Property ReCall_ImageMso() As String
        Get
            Return ResourceManager.GetString("ReCall_ImageMso", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die RecurrenceEdit ähnelt.
    '''</summary>
    Public Shared ReadOnly Property ReDial_ImageMso() As String
        Get
            Return ResourceManager.GetString("ReDial_ImageMso", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die StarRatedFull ähnelt.
    '''</summary>
    Public Shared ReadOnly Property RemoveVIP_ImageMso() As String
        Get
            Return ResourceManager.GetString("RemoveVIP_ImageMso", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die CheckNames ähnelt.
    '''</summary>
    Public Shared ReadOnly Property RWS_ImageMso() As String
        Get
            Return ResourceManager.GetString("RWS_ImageMso", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die ClipArtInsert ähnelt.
    '''</summary>
    Public Shared ReadOnly Property ShowCallMonitor_ImageMso() As String
        Get
            Return ResourceManager.GetString("ShowCallMonitor_ImageMso", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die ShowContactPage ähnelt.
    '''</summary>
    Public Shared ReadOnly Property ShowContact_ImageMso() As String
        Get
            Return ResourceManager.GetString("ShowContact_ImageMso", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
    '''</summary>
    Public Shared ReadOnly Property Tab_ImageMso() As String
        Get
            Return ResourceManager.GetString("Tab_ImageMso", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die DistributionListAddNewMember ähnelt.
    '''</summary>
    Public Shared ReadOnly Property Upload_ImageMso() As String
        Get
            Return ResourceManager.GetString("Upload_ImageMso", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die AddressBook ähnelt.
    '''</summary>
    Public Shared ReadOnly Property UploadBk_ImageMso() As String
        Get
            Return ResourceManager.GetString("UploadBk_ImageMso", resourceCulture)
        End Get
    End Property
End Class
