'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace Localize
    
    'Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    '-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    'Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    'mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    '''<summary>
    '''  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Public Class resRibbon
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("FBoxDial.resRibbon", GetType(resRibbon).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        '''  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Fügt diesen Kontakt zur VIP-Liste hinzu... ähnelt.
        '''</summary>
        Public Shared ReadOnly Property AddVIP_ScreenTipp() As String
            Get
                Return ResourceManager.GetString("AddVIP_ScreenTipp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Wahlwiederholung ähnelt.
        '''</summary>
        Public Shared ReadOnly Property CallList_Label() As String
            Get
                Return ResourceManager.GetString("CallList_Label", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Öffnet den Wähldialog für die Wahlwiederholung... ähnelt.
        '''</summary>
        Public Shared ReadOnly Property CallList_ScreenTipp() As String
            Get
                Return ResourceManager.GetString("CallList_ScreenTipp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Anrufmonitor ähnelt.
        '''</summary>
        Public Shared ReadOnly Property CallMonitor_Label() As String
            Get
                Return ResourceManager.GetString("CallMonitor_Label", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Startet oder beendert den Anrufmonitor... ähnelt.
        '''</summary>
        Public Shared ReadOnly Property CallMonitor_ScreenTipp() As String
            Get
                Return ResourceManager.GetString("CallMonitor_ScreenTipp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Einstellungen ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Config_Label() As String
            Get
                Return ResourceManager.GetString("Config_Label", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Öffnet die Einstellungen... ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Config_ScreenTipp() As String
            Get
                Return ResourceManager.GetString("Config_ScreenTipp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Kontakt erstellen ähnelt.
        '''</summary>
        Public Shared ReadOnly Property CreateContact_Label() As String
            Get
                Return ResourceManager.GetString("CreateContact_Label", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Erstellt einen neuen Kontakt... ähnelt.
        '''</summary>
        Public Shared ReadOnly Property CreateContact_ScreenTipp() As String
            Get
                Return ResourceManager.GetString("CreateContact_ScreenTipp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Liste löschen... ähnelt.
        '''</summary>
        Public Shared ReadOnly Property DeleteList_Label() As String
            Get
                Return ResourceManager.GetString("DeleteList_Label", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Lösche diese Liste... ähnelt.
        '''</summary>
        Public Shared ReadOnly Property DeleteList_ScreenTipp() As String
            Get
                Return ResourceManager.GetString("DeleteList_ScreenTipp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Wählen ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Dial_Label() As String
            Get
                Return ResourceManager.GetString("Dial_Label", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Öffnet den Wahldialog um das ausgewählte Element anzurufen... ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Dial_ScreenTipp() As String
            Get
                Return ResourceManager.GetString("Dial_ScreenTipp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Direktwahl ähnelt.
        '''</summary>
        Public Shared ReadOnly Property DirectCall_Label() As String
            Get
                Return ResourceManager.GetString("DirectCall_Label", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Öffnet den Wähldialog für die Direktwahl... ähnelt.
        '''</summary>
        Public Shared ReadOnly Property DirectCall_ScreenTipp() As String
            Get
                Return ResourceManager.GetString("DirectCall_ScreenTipp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Liste löschen... ähnelt.
        '''</summary>
        Public Shared ReadOnly Property DynListDel_Label() As String
            Get
                Return ResourceManager.GetString("DynListDel_Label", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Entfernt alle Einträge dieser Liste... ähnelt.
        '''</summary>
        Public Shared ReadOnly Property DynListDel_ScreenTipp() As String
            Get
                Return ResourceManager.GetString("DynListDel_ScreenTipp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Journalimport ähnelt.
        '''</summary>
        Public Shared ReadOnly Property JournalImport_Label() As String
            Get
                Return ResourceManager.GetString("JournalImport_Label", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Importiert die Anrufliste der Fritz!Box als Journaleinträge... ähnelt.
        '''</summary>
        Public Shared ReadOnly Property JournalImport_ScreenTipp() As String
            Get
                Return ResourceManager.GetString("JournalImport_ScreenTipp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Fritz!Box Telefonbücher ähnelt.
        '''</summary>
        Public Shared ReadOnly Property PhoneBooks_Label() As String
            Get
                Return ResourceManager.GetString("PhoneBooks_Label", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Öffne die Verwaltung der Fritz!Box Telefonbücher... ähnelt.
        '''</summary>
        Public Shared ReadOnly Property PhoneBooks_ScreenTipp() As String
            Get
                Return ResourceManager.GetString("PhoneBooks_ScreenTipp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Entfernt diesen Kontakt von der VIP-Liste... ähnelt.
        '''</summary>
        Public Shared ReadOnly Property RemoveVIP_ScreenTipp() As String
            Get
                Return ResourceManager.GetString("RemoveVIP_ScreenTipp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Rückruf ähnelt.
        '''</summary>
        Public Shared ReadOnly Property RingList_Label() As String
            Get
                Return ResourceManager.GetString("RingList_Label", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Öffnet den Wähldialog für den Rückruf... ähnelt.
        '''</summary>
        Public Shared ReadOnly Property RingList_ScreenTipp() As String
            Get
                Return ResourceManager.GetString("RingList_ScreenTipp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Rückwärtssuche ähnelt.
        '''</summary>
        Public Shared ReadOnly Property RWS_Label() As String
            Get
                Return ResourceManager.GetString("RWS_Label", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Sucht zusätzliche Informationen zu diesem Anrufer mit der Rückwärtssuche... ähnelt.
        '''</summary>
        Public Shared ReadOnly Property RWS_ScreenTipp() As String
            Get
                Return ResourceManager.GetString("RWS_ScreenTipp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Anzeigen ähnelt.
        '''</summary>
        Public Shared ReadOnly Property ShowCallMonitor_Label() As String
            Get
                Return ResourceManager.GetString("ShowCallMonitor_Label", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Zeigt den letzten Anruf an... ähnelt.
        '''</summary>
        Public Shared ReadOnly Property ShowCallMonitor_ScreenTipp() As String
            Get
                Return ResourceManager.GetString("ShowCallMonitor_ScreenTipp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Kontakt anzeigen ähnelt.
        '''</summary>
        Public Shared ReadOnly Property ShowContact_Label() As String
            Get
                Return ResourceManager.GetString("ShowContact_Label", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Zeigt den Kontakt an... ähnelt.
        '''</summary>
        Public Shared ReadOnly Property ShowContact_ScreenTipp() As String
            Get
                Return ResourceManager.GetString("ShowContact_ScreenTipp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Fritz!Box Telefon-dingsbums ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Tab_Label() As String
            Get
                Return ResourceManager.GetString("Tab_Label", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Tab_ScreenTipp() As String
            Get
                Return ResourceManager.GetString("Tab_ScreenTipp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Hochladen ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Upload_Label() As String
            Get
                Return ResourceManager.GetString("Upload_Label", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Lädt diesen Kontakt auf die Fritz!Box hoch.... ähnelt.
        '''</summary>
        Public Shared ReadOnly Property Upload_ScreenTipp() As String
            Get
                Return ResourceManager.GetString("Upload_ScreenTipp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die VIP ähnelt.
        '''</summary>
        Public Shared ReadOnly Property VIP_Label() As String
            Get
                Return ResourceManager.GetString("VIP_Label", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die VIP-Liste ähnelt.
        '''</summary>
        Public Shared ReadOnly Property VIPList_Label() As String
            Get
                Return ResourceManager.GetString("VIPList_Label", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Öffnet den Wahldialog um einen VIP anzurufen... ähnelt.
        '''</summary>
        Public Shared ReadOnly Property VIPList_ScreenTipp() As String
            Get
                Return ResourceManager.GetString("VIPList_ScreenTipp", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
