'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace Localize
    
    'Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    '-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    'Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    'mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    '''<summary>
    '''  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Public Class LocAnrMon
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("FBoxDial.LocAnrMon", GetType(LocAnrMon).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        '''  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Ausgehender Anruf zu ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strJournalAusgehend() As String
            Get
                Return ResourceManager.GetString("strJournalAusgehend", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Tel.-Nr.: ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strJournalBodyStart() As String
            Get
                Return ResourceManager.GetString("strJournalBodyStart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Telefonanrufe ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strJournalCatCalls() As String
            Get
                Return ResourceManager.GetString("strJournalCatCalls", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Fritz!Box Anrufmonitor ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strJournalCatDefault() As String
            Get
                Return ResourceManager.GetString("strJournalCatDefault", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Verpasst ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strJournalCatVerpasst() As String
            Get
                Return ResourceManager.GetString("strJournalCatVerpasst", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Eingehender Anruf von ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strJournalEingehend() As String
            Get
                Return ResourceManager.GetString("strJournalEingehend", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Journaleintrag konnte nicht erstellt werden. ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strJournalFehler() As String
            Get
                Return ResourceManager.GetString("strJournalFehler", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Nicht erfolgreicher Anruf zu ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strJournalNichterfolgreich() As String
            Get
                Return ResourceManager.GetString("strJournalNichterfolgreich", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Rückwärtssuche nicht erfolgreich: Es wurden keine Einträge gefunden. ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strJournalRWSFehler() As String
            Get
                Return ResourceManager.GetString("strJournalRWSFehler", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Kontaktdaten (vCard): ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strJournalTextvCard() As String
            Get
                Return ResourceManager.GetString("strJournalTextvCard", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Verpasster Anruf von ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strJournalVerpasst() As String
            Get
                Return ResourceManager.GetString("strJournalVerpasst", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Rufnummer unterdrückt ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strNrUnterdrückt() As String
            Get
                Return ResourceManager.GetString("strNrUnterdrückt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Soll die Nummer {0} zu der Rufsperre der Fritz!Box hinzugefügt werden? ähnelt.
        '''</summary>
        Public Shared ReadOnly Property strQuestionBlockNumber() As String
            Get
                Return ResourceManager.GetString("strQuestionBlockNumber", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
